<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>2&nbsp; Essentials of Normal Linear Models – MATH3823 Generalised Linear Models</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./3_GLM-Theory.html" rel="next">
<link href="./1_intro.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="webex.css">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./2_linearmodels.html"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Essentials of Normal Linear Models</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">MATH3823 Generalised Linear Models</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Weekly schedule</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0_preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Overview</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./1_intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./2_linearmodels.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Essentials of Normal Linear Models</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./3_GLM-Theory.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">GLM Theory</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./4_GLM-Fitting.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">GLM Estimation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./5_logisticmodel.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Modelling Proportions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./6_loglinearmodel.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Loglinear Models</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./7_extendedloglinearmodel.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Extensions to Loglinear models</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#sec-essentialsoverview" id="toc-sec-essentialsoverview" class="nav-link active" data-scroll-target="#sec-essentialsoverview"><span class="header-section-number">2.1</span> Overview</a></li>
  <li><a href="#focus-on-modelling-quiz" id="toc-focus-on-modelling-quiz" class="nav-link" data-scroll-target="#focus-on-modelling-quiz">Focus on modelling quiz</a></li>
  <li><a href="#linear-models" id="toc-linear-models" class="nav-link" data-scroll-target="#linear-models"><span class="header-section-number">2.2</span> Linear models</a></li>
  <li><a href="#focus-on-regression-quiz" id="toc-focus-on-regression-quiz" class="nav-link" data-scroll-target="#focus-on-regression-quiz">Focus on regression quiz</a></li>
  <li><a href="#sec-typesnormalvariable" id="toc-sec-typesnormalvariable" class="nav-link" data-scroll-target="#sec-typesnormalvariable"><span class="header-section-number">2.3</span> Types of normal linear model</a></li>
  <li><a href="#sec-matrix" id="toc-sec-matrix" class="nav-link" data-scroll-target="#sec-matrix"><span class="header-section-number">2.4</span> Matrix representation of linear models</a></li>
  <li><a href="#focus-on-matrix-representations-quiz" id="toc-focus-on-matrix-representations-quiz" class="nav-link" data-scroll-target="#focus-on-matrix-representations-quiz">Focus on matrix representations quiz</a></li>
  <li><a href="#sec-shorthand" id="toc-sec-shorthand" class="nav-link" data-scroll-target="#sec-shorthand"><span class="header-section-number">2.5</span> Model shorthand notation</a></li>
  <li><a href="#focus-on-model-notation-quiz" id="toc-focus-on-model-notation-quiz" class="nav-link" data-scroll-target="#focus-on-model-notation-quiz">Focus on model notation quiz</a></li>
  <li><a href="#fitting-linear-models-in-r" id="toc-fitting-linear-models-in-r" class="nav-link" data-scroll-target="#fitting-linear-models-in-r"><span class="header-section-number">2.6</span> Fitting linear models in <strong>R</strong></a></li>
  <li><a href="#ethics-in-statistics-and-data-science" id="toc-ethics-in-statistics-and-data-science" class="nav-link" data-scroll-target="#ethics-in-statistics-and-data-science"><span class="header-section-number">2.7</span> Ethics in statistics and data science</a></li>
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises"><span class="header-section-number">2.8</span> Exercises</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Essentials of Normal Linear Models</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="sec-essentialsoverview" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="sec-essentialsoverview"><span class="header-section-number">2.1</span> Overview</h2>
<p>In many fields of application, we might assume the response variable is normally distributed. For example: heights, weights, log prices, etc.</p>
<p>The data<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> in <a href="#tbl-birthweight" class="quarto-xref">Table&nbsp;<span>2.1</span></a> record the birth weights of 12 girls and 12 boys and their gestational ages (time from conception to birth).</p>
<div id="tbl-birthweight" class="quarto-layout-panel anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-birthweight-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2.1: Gestational ages (in weeks) and birth weights (in grams) for 24 babies (12 girls and 12 boys).
</figcaption>
<div aria-describedby="tbl-birthweight-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<table class="caption-top table">
<caption>Girls</caption>
<thead>
<tr class="header">
<th style="text-align: center;">Gestational Age</th>
<th style="text-align: center;">Birth weight</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">40</td>
<td style="text-align: center;">3317</td>
</tr>
<tr class="even">
<td style="text-align: center;">36</td>
<td style="text-align: center;">2729</td>
</tr>
<tr class="odd">
<td style="text-align: center;">40</td>
<td style="text-align: center;">2935</td>
</tr>
<tr class="even">
<td style="text-align: center;">37</td>
<td style="text-align: center;">2754</td>
</tr>
<tr class="odd">
<td style="text-align: center;">42</td>
<td style="text-align: center;">3210</td>
</tr>
<tr class="even">
<td style="text-align: center;">39</td>
<td style="text-align: center;">2817</td>
</tr>
<tr class="odd">
<td style="text-align: center;">40</td>
<td style="text-align: center;">3126</td>
</tr>
<tr class="even">
<td style="text-align: center;">37</td>
<td style="text-align: center;">2539</td>
</tr>
<tr class="odd">
<td style="text-align: center;">36</td>
<td style="text-align: center;">2412</td>
</tr>
<tr class="even">
<td style="text-align: center;">38</td>
<td style="text-align: center;">2991</td>
</tr>
<tr class="odd">
<td style="text-align: center;">39</td>
<td style="text-align: center;">2875</td>
</tr>
<tr class="even">
<td style="text-align: center;">40</td>
<td style="text-align: center;">3231</td>
</tr>
</tbody>
</table>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<table class="caption-top table">
<caption>Boys</caption>
<thead>
<tr class="header">
<th style="text-align: center;">Gestational Age</th>
<th style="text-align: center;">Birth weight</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">40</td>
<td style="text-align: center;">2968</td>
</tr>
<tr class="even">
<td style="text-align: center;">38</td>
<td style="text-align: center;">2795</td>
</tr>
<tr class="odd">
<td style="text-align: center;">40</td>
<td style="text-align: center;">3163</td>
</tr>
<tr class="even">
<td style="text-align: center;">35</td>
<td style="text-align: center;">2925</td>
</tr>
<tr class="odd">
<td style="text-align: center;">36</td>
<td style="text-align: center;">2625</td>
</tr>
<tr class="even">
<td style="text-align: center;">37</td>
<td style="text-align: center;">2847</td>
</tr>
<tr class="odd">
<td style="text-align: center;">41</td>
<td style="text-align: center;">3292</td>
</tr>
<tr class="even">
<td style="text-align: center;">40</td>
<td style="text-align: center;">3473</td>
</tr>
<tr class="odd">
<td style="text-align: center;">37</td>
<td style="text-align: center;">2628</td>
</tr>
<tr class="even">
<td style="text-align: center;">38</td>
<td style="text-align: center;">3176</td>
</tr>
<tr class="odd">
<td style="text-align: center;">40</td>
<td style="text-align: center;">3421</td>
</tr>
<tr class="even">
<td style="text-align: center;">38</td>
<td style="text-align: center;">3975</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</figure>
</div>
<p>A key question is, can we predict the birth weight of a baby born at a given gestational age using these data. For this we will need to make assumptions about the relationship between birth weight and gestational age, and any associated natural variation – that is we require a model.</p>
<p>First we should explore the data. <a href="#fig-birthweightA-1" class="quarto-xref">Figure&nbsp;<span>2.1 (a)</span></a> shows a histogram of the birth weights indicating a spread around modal group 2800-3000 grams; <a href="#fig-birthweightA-2" class="quarto-xref">Figure&nbsp;<span>2.1 (b)</span></a> indicates slightly higher birth weights for the boys than the girls; and <a href="#fig-birthweightA-3" class="quarto-xref">Figure&nbsp;<span>2.1 (c)</span></a> shows an increasing relationship between weight and age. Together, these suggest that gestational age and sex are likely to be important for predicting weight.</p>
<div class="cell" data-layout="[[1,1],[1]]">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mar=</span><span class="fu">c</span>(<span class="dv">4</span>,<span class="dv">4</span>,<span class="dv">0</span>,<span class="dv">1</span>))</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>birthweight <span class="ot">=</span> <span class="fu">read.table</span>(<span class="st">"https://richardpmann.github.io/MATH3823/Datasets/birthwt-numeric.txt"</span>, <span class="at">header=</span>T)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>weight <span class="ot">=</span> birthweight<span class="sc">$</span>weight</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>age <span class="ot">=</span> birthweight<span class="sc">$</span>age</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>sex <span class="ot">=</span> birthweight<span class="sc">$</span>sex</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(weight, <span class="at">breaks=</span><span class="dv">6</span>, <span class="at">probability =</span> T, <span class="at">main =</span> <span class="st">""</span>, </span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Birth weight (grams)"</span>)</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(weight<span class="sc">~</span>sex, <span class="at">names=</span><span class="fu">c</span>(<span class="st">"Girl"</span>, <span class="st">"Boy"</span>))</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(age, weight, <span class="at">pch=</span><span class="dv">16</span>, </span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Gestational age (weeks)"</span>,</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"Birth weight (grams)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div id="fig-birthweightA" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-birthweightA-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-birthweightA" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-birthweightA-1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-birthweightA-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="2_linearmodels_files/figure-html/fig-birthweightA-1.png" class="img-fluid figure-img" data-ref-parent="fig-birthweightA" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-birthweightA-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) Weight distribution
</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-birthweightA" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-birthweightA-2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-birthweightA-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="2_linearmodels_files/figure-html/fig-birthweightA-2.png" class="img-fluid figure-img" data-ref-parent="fig-birthweightA" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-birthweightA-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b) Weight sub-divided by Sex
</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-birthweightA" style="flex-basis: 100.0%;justify-content: flex-start;">
<div id="fig-birthweightA-3" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-birthweightA-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="2_linearmodels_files/figure-html/fig-birthweightA-3.png" class="img-fluid figure-img" data-ref-parent="fig-birthweightA" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-birthweightA-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(c) Relationship beween variables
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-birthweightA-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2.1: Birthweight and gestational age for 24 babies.
</figcaption>
</figure>
</div>
</div>
<p>Before considering possible models, <a href="#fig-birthweightB" class="quarto-xref">Figure&nbsp;<span>2.2</span></a> again shows the relationship between weight and age but this time with the points coloured according to the baby’s sex. This, perhaps, shows the boys to have generally higher weights across the age range than girls.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mar=</span><span class="fu">c</span>(<span class="dv">4</span>,<span class="dv">4</span>,<span class="dv">0</span>,<span class="dv">1</span>))</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>birthweight <span class="ot">=</span> <span class="fu">read.table</span>(<span class="st">"https://richardpmann.github.io/MATH3823/Datasets/birthwt-numeric.txt"</span>, <span class="at">header=</span>T)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>weight <span class="ot">=</span> birthweight<span class="sc">$</span>weight</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>age <span class="ot">=</span> birthweight<span class="sc">$</span>age</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>sex <span class="ot">=</span> birthweight<span class="sc">$</span>sex</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(age, weight, <span class="at">col=</span><span class="dv">2</span><span class="sc">-</span>sex, <span class="at">pch=</span><span class="dv">15-11</span><span class="sc">*</span>sex,</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Gestational age (weeks)"</span>,</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"Birth weight (grams)"</span>)</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="dv">41</span>,<span class="dv">2800</span>, <span class="fu">c</span>(<span class="st">"Girl"</span>,<span class="st">"Boy"</span>), <span class="at">col =</span> <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">1</span>), <span class="at">pch=</span><span class="fu">c</span>(<span class="dv">15</span>,<span class="dv">4</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-birthweightB" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-birthweightB-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="2_linearmodels_files/figure-html/fig-birthweightB-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-birthweightB-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2.2: Birthweight and gestational age for 12 girls (red squares) and 12 boys (black crosses).
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="focus-on-modelling-quiz" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="focus-on-modelling-quiz">Focus on modelling quiz</h2>
<p>Test your knowledge recall and application to reinforce basic ideas and prepare for similar concepts later in the module.</p>
<div class="webex-box">
<div class="webex-check">
<p>For each situation, choose one of the following statements which you think is <strong>most likely</strong> to apply.</p>
<ol type="1">
<li><p>What is the most useful graphical summary for identifying a potential relationship between two variables? <select class="webex-select"><option value="blank"></option><option value="">boxplot</option><option value="">histogram</option><option value="answer">scatter plot</option><option value="">kernel density plot</option><option value="">other</option></select></p></li>
<li><p>What is the most useful numerical summary for identifying a potential linear relationship between two variables? <select class="webex-select"><option value="blank"></option><option value="">skew</option><option value="">variances</option><option value="">sample means</option><option value="answer">correlation</option><option value="">other</option></select></p></li>
<li><p>Which of the following is a true statements about the correlation coefficient? (Choose any that apply.)</p>
<div id="radio_RHKMQOQWJX" class="webex-radiogroup">
<label><input type="radio" autocomplete="off" name="radio_RHKMQOQWJX" value="answer"> <span>Can be positive or negative</span></label><label><input type="radio" autocomplete="off" name="radio_RHKMQOQWJX" value="answer"> <span>Is always between -1 and +1</span></label><label><input type="radio" autocomplete="off" name="radio_RHKMQOQWJX" value=""> <span>Can take any real number</span></label><label><input type="radio" autocomplete="off" name="radio_RHKMQOQWJX" value=""> <span>A value close to -1 means uncorrelated and close to +1 indicates a high correlation</span></label><label><input type="radio" autocomplete="off" name="radio_RHKMQOQWJX" value=""> <span>Is always a positive number</span></label>
</div></li>
<li><p>Which of the following is a true statements about regression? (Choose any that apply.)</p>
<div id="radio_FHXQRVTFQA" class="webex-radiogroup">
<label><input type="radio" autocomplete="off" name="radio_FHXQRVTFQA" value="answer"> <span>After fitting a regression model we should always consider residuals</span></label><label><input type="radio" autocomplete="off" name="radio_FHXQRVTFQA" value=""> <span>All regression models describe linear relationships</span></label><label><input type="radio" autocomplete="off" name="radio_FHXQRVTFQA" value="answer"> <span>A linear regression can sometimes be used to approximate a non-linear relationship</span></label><label><input type="radio" autocomplete="off" name="radio_FHXQRVTFQA" value=""> <span>A linear regression model will fit well if the correlation is close to zero</span></label><label><input type="radio" autocomplete="off" name="radio_FHXQRVTFQA" value="answer"> <span>A linear model can be fitted to any data set</span></label>
</div></li>
<li><p>Which of the following is a true statements about statistical modelling? (Choose any that apply.)</p>
<div id="radio_SDADIKESJF" class="webex-radiogroup">
<label><input type="radio" autocomplete="off" name="radio_SDADIKESJF" value="answer"> <span>Models are part deterministic and part random</span></label><label><input type="radio" autocomplete="off" name="radio_SDADIKESJF" value=""> <span>Models only involve a statistical distribution</span></label><label><input type="radio" autocomplete="off" name="radio_SDADIKESJF" value="answer"> <span>All models are approximations</span></label><label><input type="radio" autocomplete="off" name="radio_SDADIKESJF" value=""> <span>Only use a linear model</span></label><label><input type="radio" autocomplete="off" name="radio_SDADIKESJF" value=""> <span>Only use a model that is 100% correct</span></label>
</div></li>
</ol>
</div>
</div>
</section>
<section id="linear-models" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="linear-models"><span class="header-section-number">2.2</span> Linear models</h2>
<p>Continuing the birth weight example. Of course, there are very many possible models, but here we will consider the following:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 37%">
<col style="width: 62%">
</colgroup>
<tbody>
<tr class="odd">
<td><span class="math inline">\(\texttt{Model 0}:\)</span></td>
<td><span class="math inline">\(\texttt{Weight}=\alpha\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(\texttt{Model 1}:\)</span></td>
<td><span class="math inline">\(\texttt{Weight}=\alpha + \beta.\texttt{Age}\)</span></td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\texttt{Model 2}:\)</span></td>
<td><span class="math inline">\(\texttt{Weight}=\alpha + \beta.\texttt{Age}+\gamma.\texttt{Sex}\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(\texttt{Model 3}:\)</span></td>
<td><span class="math inline">\(\texttt{Weight}=\alpha + \beta.\texttt{Age}+\gamma.\texttt{Sex} + \delta.\texttt{Age}.\texttt{Sex}\)</span></td>
</tr>
</tbody>
</table>
<p>In these models, <span class="math inline">\(\texttt{Weight}\)</span> is called the <em>response</em> variable (sometimes called the <em>dependent</em> variable) and <span class="math inline">\(\texttt{Age}\)</span> and <span class="math inline">\(\texttt{Sex}\)</span> are called the <em>covariates</em> or <em>explanatory</em> variables (sometimes called the <em>predictor</em> or <em>independent</em> variables). Here, <span class="math inline">\(\texttt{Age}\)</span> is a continuous variable whereas <span class="math inline">\(\texttt{Sex}\)</span> is coded as a <em>dummy</em> variable taking the value 0 for girls and 1 for boys; it is an example of a <em>factor</em>, in this case with just two <em>levels</em>: Girl and Boy.</p>
<p>Note that <span class="math inline">\(\texttt{Model 0}\)</span> is a special case of <span class="math inline">\(\texttt{Model 1}\)</span> (consider the situation when <span class="math inline">\(\beta=0\)</span>) and that <span class="math inline">\(\texttt{Model 1}\)</span> is a special case of <span class="math inline">\(\texttt{Model 2}\)</span> (consider the situation when <span class="math inline">\(\gamma=0\)</span>) and finally that <span class="math inline">\(\texttt{Model 2}\)</span> is a special case of <span class="math inline">\(\texttt{Model 3}\)</span> (consider the situation when <span class="math inline">\(\delta=0\)</span>) – such models are called <em>nested</em>.</p>
<p>In these models, <span class="math inline">\(\alpha\)</span>, <span class="math inline">\(\beta\)</span>, <span class="math inline">\(\gamma\)</span> and <span class="math inline">\(\delta\)</span> are <em>model parameters</em>. Parameter <span class="math inline">\(\alpha\)</span> is called the <em>intercept</em> term; <span class="math inline">\(\beta\)</span> is called the <em>main effect</em> of <span class="math inline">\(\texttt{Age}\)</span>; and is interpreted as the effect on birth weight <em>per week</em> of gestational age. Similarly, <span class="math inline">\(\gamma\)</span> is the main effect of <span class="math inline">\(\texttt{Sex}\)</span>, interpreted as the effect on birth weight of being a boy (because girl is the <em>baseline</em> category).</p>
<p>Parameter <span class="math inline">\(\delta\)</span> is called the <em>interaction effect</em> between <span class="math inline">\(\texttt{Age}\)</span> and <span class="math inline">\(\texttt{Sex}\)</span>. <strong>Take care when interpreting an interaction effect.</strong> Here, it does not mean that age somehow affects sex, or vice-versa. It means that the effect of gestational age on birth weight depends on whether the baby is a boy or a girl.</p>
<p>These models can be fitted to the data using (Ordinary) <em>Least Squares</em> to produce the results presented in <a href="#fig-birthweight-fitted" class="quarto-xref">Figure&nbsp;<span>2.3</span></a>.</p>
<p>Which model should we use?</p>
<div class="cell" data-layout="[[1,1],[1,1]]">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mar=</span><span class="fu">c</span>(<span class="dv">4</span>,<span class="dv">4</span>,<span class="dv">0</span>,<span class="dv">1</span>))</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>birthweight <span class="ot">=</span> <span class="fu">read.table</span>(<span class="st">"https://richardpmann.github.io/MATH3823/Datasets/birthwt-numeric.txt"</span>, <span class="at">header=</span>T)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>weight <span class="ot">=</span> birthweight<span class="sc">$</span>weight</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>age <span class="ot">=</span> birthweight<span class="sc">$</span>age</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>sex <span class="ot">=</span> birthweight<span class="sc">$</span>sex</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(age, weight, <span class="at">pch=</span><span class="dv">16</span>, </span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Gestational age (weeks)"</span>,</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"Birth weight (grams)"</span>)</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="fu">mean</span>(weight))</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(age, weight, <span class="at">pch=</span><span class="dv">16</span>,  </span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Gestational age (weeks)"</span>,</span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"Birth weight (grams)"</span>)</span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a>M1.fit <span class="ot">=</span> <span class="fu">lm</span>(weight<span class="sc">~</span>age)</span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(M1.fit<span class="sc">$</span>coefficients[<span class="dv">1</span>],M1.fit<span class="sc">$</span>coefficients[<span class="dv">2</span>])</span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(age, weight, <span class="at">pch=</span><span class="dv">15-11</span><span class="sc">*</span>sex, <span class="at">col=</span><span class="dv">2</span><span class="sc">-</span>sex, </span>
<span id="cb3-23"><a href="#cb3-23" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Gestational age (weeks)"</span>,</span>
<span id="cb3-24"><a href="#cb3-24" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"Birth weight (grams)"</span>)</span>
<span id="cb3-25"><a href="#cb3-25" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="dv">41</span>,<span class="dv">2800</span>, <span class="fu">c</span>(<span class="st">"Girl"</span>,<span class="st">"Boy"</span>), <span class="at">col =</span> <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">1</span>),<span class="at">pch=</span><span class="fu">c</span>(<span class="dv">15</span>,<span class="dv">4</span>))</span>
<span id="cb3-26"><a href="#cb3-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-27"><a href="#cb3-27" aria-hidden="true" tabindex="-1"></a>M2.fit <span class="ot">=</span> <span class="fu">lm</span>(weight<span class="sc">~</span>age<span class="sc">+</span>sex)</span>
<span id="cb3-28"><a href="#cb3-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-29"><a href="#cb3-29" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(M2.fit<span class="sc">$</span>coefficients[<span class="dv">1</span>],M2.fit<span class="sc">$</span>coefficients[<span class="dv">2</span>], <span class="at">col=</span><span class="dv">2</span>)</span>
<span id="cb3-30"><a href="#cb3-30" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(M2.fit<span class="sc">$</span>coefficients[<span class="dv">1</span>]<span class="sc">+</span>M2.fit<span class="sc">$</span>coefficients[<span class="dv">3</span>],M2.fit<span class="sc">$</span>coefficients[<span class="dv">2</span>], <span class="at">col=</span><span class="dv">1</span>)</span>
<span id="cb3-31"><a href="#cb3-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-32"><a href="#cb3-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-33"><a href="#cb3-33" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(age, weight, <span class="at">pch=</span><span class="dv">15</span><span class="sc">+</span>sex, <span class="at">col=</span><span class="dv">2</span><span class="sc">-</span>sex, </span>
<span id="cb3-34"><a href="#cb3-34" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Gestational age (weeks)"</span>,</span>
<span id="cb3-35"><a href="#cb3-35" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"Birth weight (grams)"</span>)</span>
<span id="cb3-36"><a href="#cb3-36" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="dv">41</span>,<span class="dv">2800</span>, <span class="fu">c</span>(<span class="st">"Girl"</span>,<span class="st">"Boy"</span>), <span class="at">col =</span> <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">1</span>), <span class="at">pch=</span><span class="fu">c</span>(<span class="dv">15</span>,<span class="dv">16</span>))</span>
<span id="cb3-37"><a href="#cb3-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-38"><a href="#cb3-38" aria-hidden="true" tabindex="-1"></a>M3.fit <span class="ot">=</span> <span class="fu">lm</span>(weight<span class="sc">~</span>age<span class="sc">+</span>sex<span class="sc">+</span>age<span class="sc">*</span>sex)</span>
<span id="cb3-39"><a href="#cb3-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-40"><a href="#cb3-40" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(M3.fit<span class="sc">$</span>coefficients[<span class="dv">1</span>],M3.fit<span class="sc">$</span>coefficients[<span class="dv">2</span>], <span class="at">col=</span><span class="dv">2</span>)</span>
<span id="cb3-41"><a href="#cb3-41" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(M3.fit<span class="sc">$</span>coefficients[<span class="dv">1</span>]<span class="sc">+</span>M3.fit<span class="sc">$</span>coefficients[<span class="dv">3</span>],M3.fit<span class="sc">$</span>coefficients[<span class="dv">2</span>]<span class="sc">+</span>M3.fit<span class="sc">$</span>coefficients[<span class="dv">4</span>], <span class="at">col=</span><span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div id="fig-birthweight-fitted" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-birthweight-fitted-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-birthweight-fitted" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-birthweight-fitted-1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-birthweight-fitted-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="2_linearmodels_files/figure-html/fig-birthweight-fitted-1.png" class="img-fluid figure-img" data-ref-parent="fig-birthweight-fitted" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-birthweight-fitted-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) Model 0
</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-birthweight-fitted" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-birthweight-fitted-2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-birthweight-fitted-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="2_linearmodels_files/figure-html/fig-birthweight-fitted-2.png" class="img-fluid figure-img" data-ref-parent="fig-birthweight-fitted" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-birthweight-fitted-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b) Model 1
</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-birthweight-fitted" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-birthweight-fitted-3" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-birthweight-fitted-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="2_linearmodels_files/figure-html/fig-birthweight-fitted-3.png" class="img-fluid figure-img" data-ref-parent="fig-birthweight-fitted" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-birthweight-fitted-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(c) Model 2
</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-birthweight-fitted" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-birthweight-fitted-4" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-birthweight-fitted-4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="2_linearmodels_files/figure-html/fig-birthweight-fitted-4.png" class="img-fluid figure-img" data-ref-parent="fig-birthweight-fitted" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-birthweight-fitted-4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(d) Model 3
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-birthweight-fitted-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2.3: Birthweight and gestational age data with superimposed fitted regression lines from various competing models.
</figcaption>
</figure>
</div>
</div>
<p>We know from previous modules that statistical tests can be used to check the importance of regression coefficients and model parameters, but it is also important to use the graphical results, as in <a href="#fig-birthweight-fitted" class="quarto-xref">Figure&nbsp;<span>2.3</span></a>, to guide us.</p>
<p><span class="math inline">\(\texttt{Model 0}\)</span> says that there is no change in birth weight with gestational age which means that we would use the average birth weight as the prediction whatever the gestational age – this makes no sense. As we can easily see from the scatter plot of the data, the fitted line in this case is clearly inappropriate.</p>
<p><span class="math inline">\(\texttt{Model 1}\)</span> does not take into account whether the baby is a girl or a boy, but does model the relationship between birth weight and gestational age. This does seem to provide a good fit and might be adequate for many purposes. Recall from <a href="#fig-birthweightA-2" class="quarto-xref">Figure&nbsp;<span>2.1 (b)</span></a> and <a href="#fig-birthweightB" class="quarto-xref">Figure&nbsp;<span>2.2</span></a>, however, that for a given gestational age the boys seem to have a higher birth weight than the girls.</p>
<p><span class="math inline">\(\texttt{Model 2}\)</span> does take the sex of the baby into account by allowing separate intercepts in the fitted lines – this means that the lines are parallel. By eye, there is a clear difference between these two lines but it might not be important.</p>
<p><span class="math inline">\(\texttt{Model 3}\)</span> allows for separate slopes as well as intercepts. There is a slight difference in the slopes, with the birth weight of the girls gradually catching-up as the gestational age increases. It is difficult to see, however, if this will be a general pattern or if it is only true for this data set – especially given the relatively small sample size.</p>
<p>Here, it is not clear by eye which of the fitted models will be the best and hence we should use a statistical test to help. In particular, we can choose between the models using F-tests.</p>
<p>Let <span class="math inline">\(y_i\)</span> denote the value of the dependent variable <span class="math inline">\(\texttt{Weight}\)</span> for individual <span class="math inline">\(i=1,\dots,n\)</span>, and let the four models be indexed by <span class="math inline">\(k=0,1,2,3\)</span>.</p>
<p>Let <span class="math inline">\(R_k\)</span> denote the <em>residual sum of squares</em> (RSS) for Model <span class="math inline">\(k:\)</span></p>
<p><span id="eq-rss"><span class="math display">\[
R_k = \sum_{i=1}^n (y_i - \hat{\mu}_{ki})^2,
\tag{2.1}\]</span></span></p>
<p>where <span class="math inline">\(\hat{\mu}_{ki}\)</span> is the fitted value for individual <span class="math inline">\(i\)</span> under <span class="math inline">\(\texttt{Model}\)</span> <span class="math inline">\(k\)</span>. Let <span class="math inline">\(r_k\)</span> denote the corresponding <em>residual degrees of freedom</em> for <span class="math inline">\(\texttt{Model}\)</span> <span class="math inline">\(k\)</span> (the number of observations minus the number of model parameters).</p>
<p>Consider the following hypotheses: <span class="math display">\[
H_0: \texttt{Model } 0 \text{ is true}; \hspace{5mm} H_1: \texttt{Model } 1 \text{ is true}.
\]</span> Under the null hypothesis <span class="math inline">\(H_0\)</span>, the difference between <span class="math inline">\(R_0\)</span> and <span class="math inline">\(R_1\)</span> will be purely random, so the between-models mean-square <span class="math inline">\((R_0 - R_1)/(r_0 - r_1)\)</span> should be comparable to the residual mean-square <span class="math inline">\(R_1/r_1\)</span>. Thus our test statistic for comparing <span class="math inline">\(\texttt{Model } 1\)</span> to the simpler <span class="math inline">\(\texttt{Model } 0\)</span> is:</p>
<p><span id="eq-f01"><span class="math display">\[
F_{01} = \frac{(R_0 - R_1)/(r_0 - r_1)}{R_1/r_1}.
\tag{2.2}\]</span></span></p>
<p>It can be shown that, under the null hypothesis <span class="math inline">\(H_0\)</span>, the statistic <span class="math inline">\(F_{01}\)</span> will have an <span class="math inline">\(F\)</span>-distribution on <span class="math inline">\(r_0 - r_1\)</span> and <span class="math inline">\(r_1\)</span> degrees of freedom, which we write: <span class="math inline">\(F_{r_0-r_1, r_1}\)</span>. Under the alternative hypothesis <span class="math inline">\(H_1\)</span>, the difference <span class="math inline">\(R_0-R_1\)</span> will tend to be larger than expected under <span class="math inline">\(H_0\)</span>, and so the observed value <span class="math inline">\(F_{01}\)</span> will probably lie in the upper tail of the <span class="math inline">\(F_{r_0-r_1, r_1}\)</span> distribution.</p>
<p>Returning to the birth weight data, we obtain the following output from <strong>R</strong> when we fit <span class="math inline">\(\texttt{Model } 1\)</span>:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># read the data from file into a dataframe called ’birthweight’</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>birthweight <span class="ot">=</span> <span class="fu">read.table</span>(<span class="st">"https://richardpmann.com/MATH3823/Datasets/birthwt.txt"</span>, <span class="at">header=</span>T)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="co"># fit Model 1</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>fit1 <span class="ot">=</span> <span class="fu">lm</span>(weight <span class="sc">~</span> age, <span class="at">data=</span>birthweight)</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a><span class="co"># print the parameter estimates from Model 1</span></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a><span class="fu">coefficients</span>(fit1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)         age 
 -1484.9846    115.5283 </code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># perform an analysis of variance of Model 1</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(fit1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: weight
          Df  Sum Sq Mean Sq F value   Pr(&gt;F)    
age        1 1013799 1013799   27.33 3.04e-05 ***
Residuals 22  816074   37094                     
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Thus we have parameter estimates: <span class="math inline">\(\hat\alpha = -1484.98\)</span> and <span class="math inline">\(\hat\beta = 115.5\)</span>. The Analysis of Variance (ANOVA) table gives: <span class="math inline">\(R_0-R_1 = 1013799\)</span> with <span class="math inline">\(r_0-r_1 = 1\)</span> and <span class="math inline">\(R_1 = 816074\)</span> with <span class="math inline">\(r_1 = 22\)</span>.</p>
<p>If we wanted <span class="math inline">\(R_0\)</span> and <span class="math inline">\(r_0\)</span> then we can either fit <span class="math inline">\(\texttt{Model 0}\)</span> or get them <em>by subtraction.</em></p>
<p>The <span class="math inline">\(F_{01}\)</span> statistic, <a href="#eq-f01" class="quarto-xref">Equation&nbsp;<span>2.2</span></a>, is then <span class="math display">\[
F_{01} = \frac{1013799/1}{816074/22} = 27.33,
\]</span> which can be read directly from the ANOVA table in the column headed ‘F value’.</p>
<p>Is <span class="math inline">\(F_{01} = 27.33\)</span> in the upper tail of the <span class="math inline">\(F_{1,22}\)</span> distribution? (See <a href="#fig-f01-pdf" class="quarto-xref">Figure&nbsp;<span>2.4</span></a> and note that 27.33 is very far to the right.) The final column of the ANOVA table tells us that the probability of observing <span class="math inline">\(F_{01} &gt; 27.33\)</span> is only <span class="math inline">\(3.04\times10^{-5}\)</span> – this is called a p-value. The *** beside this p-value highlights that its value lies between 0 and 0.001. This indicates that we should reject <span class="math inline">\(H_0\)</span> in favour of <span class="math inline">\(H_1\)</span> – there is very strong evidence for the more complicated model. Thus we would conclude that the effect of gestational age is statistically significant in these data.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mar=</span><span class="fu">c</span>(<span class="dv">4</span>,<span class="dv">4</span>,<span class="dv">0</span>,<span class="dv">1</span>))</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="fu">curve</span>(<span class="fu">df</span>(x,<span class="dv">1</span>,<span class="dv">22</span>), <span class="dv">0</span>,<span class="dv">30</span>, </span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>      <span class="at">ylab=</span><span class="fu">expression</span>(<span class="st">"PDF of "</span><span class="sc">*</span><span class="st">"F"</span>[<span class="dv">0</span>][<span class="dv">1</span>]))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-f01-pdf" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-f01-pdf-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="2_linearmodels_files/figure-html/fig-f01-pdf-1.png" class="img-fluid figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-f01-pdf-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2.4: Probability density function of <span class="math inline">\(F_{01}\)</span> distribution.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Next, consider the following hypotheses:</p>
<p><span class="math display">\[
H_0: \texttt{Model } 1 \text{ is true}; \hspace{5mm} H_1: \texttt{Model } 2 \text{ is true}.
\]</span></p>
<p>Under the null hypothesis <span class="math inline">\(H_0\)</span>, the difference between <span class="math inline">\(R_1\)</span> and <span class="math inline">\(R_2\)</span> will be purely random, so the between-models mean-square <span class="math inline">\((R_1 - R_2)/(r_1 - r_2)\)</span> should be comparable to the residual mean-square <span class="math inline">\(R_2/r_2\)</span>. Thus our test statistic for comparing <span class="math inline">\(\texttt{Model } 2\)</span> to the simpler <span class="math inline">\(\texttt{Model } 1\)</span> is:</p>
<p><span id="eq-f12"><span class="math display">\[
F_{12} = \frac{(R_1 - R_2)/(r_1 - r_2)}{R_2/r_2}.
\tag{2.3}\]</span></span></p>
<p>Under the null hypothesis <span class="math inline">\(H_0\)</span>, the statistic <span class="math inline">\(F_{12}\)</span> will have an <span class="math inline">\(F\)</span>-distribution on <span class="math inline">\(r_1 - r_2\)</span> and <span class="math inline">\(r_2\)</span> degrees of freedom, which we write: <span class="math inline">\(F_{r_1-r_2, r_2}\)</span>. Under the alternative hypothesis <span class="math inline">\(H_1\)</span>, the difference <span class="math inline">\(R_1-R_2\)</span> will tend to be larger than expected under <span class="math inline">\(H_0\)</span>, and so the observed value <span class="math inline">\(F_{12}\)</span> will probably lie in the upper tail of the <span class="math inline">\(F_{r_1-r_2, r_2}\)</span> distribution.</p>
<p>Returning to the birth weight data, we obtain the following output from <strong>R</strong> (where <span class="math inline">\(\texttt{sexM}\)</span> denotes Boy):</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># fit Model 2</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>fit2 <span class="ot">=</span> <span class="fu">lm</span>(weight <span class="sc">~</span> age <span class="sc">+</span> sex, <span class="at">data=</span>birthweight)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="co"># print the parameter estimates from Model 2</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="fu">coefficients</span>(fit2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)         age        sexM 
 -1773.3218    120.8943    163.0393 </code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># perform an analysis of variance on the fitted model</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(fit2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: weight
          Df  Sum Sq Mean Sq F value    Pr(&gt;F)    
age        1 1013799 1013799 32.3174 1.213e-05 ***
sex        1  157304  157304  5.0145   0.03609 *  
Residuals 21  658771   31370                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Thus we have parameter estimates: <span class="math inline">\(\hat \alpha = -1773.3\)</span>, <span class="math inline">\(\hat\beta = 120.9\)</span> and <span class="math inline">\(\hat\gamma = 163.0\)</span>, the latter being the effect of being a boy compared to the baseline category of being a girl.</p>
<p>The Analysis of Variance (ANOVA) table gives: <span class="math inline">\(R_1-R_2 = 157304\)</span> with <span class="math inline">\(r_1-r_2=1\)</span>, and <span class="math inline">\(R_2=658771\)</span> with <span class="math inline">\(r_2=21\)</span>. The <span class="math inline">\(F_{12}\)</span> statistic, <a href="#eq-f12" class="quarto-xref">Equation&nbsp;<span>2.3</span></a>, is then</p>
<p><span class="math display">\[
F_{12} = \frac{157304/1}{658771/21} = 5.0145,
\]</span></p>
<p>which can be read directly from the ANOVA table in the column headed ‘F value’. Is <span class="math inline">\(F_{12} = 5.01\)</span> in the upper tail of the <span class="math inline">\(F_{1,21}\)</span> distribution?</p>
<p>The final column of the ANOVA table tells us that the probability of observing <span class="math inline">\(F_{12} &gt; 5.01\)</span> is only <span class="math inline">\(0.03609\)</span> – this is called a p-value. The * beside this p-value highlights that its value lies between 0.01 and 0.05. This indicates that we should reject <span class="math inline">\(H_0\)</span> in favour of <span class="math inline">\(H_1\)</span> – there is evidence for the more complicated model. Thus we would conclude that the effect of the sex of the baby, after controlling for gestational age, is statistically significant in these data.</p>
<p>To complete the analysis, we should now compare <span class="math inline">\(\texttt{Model }2\)</span> with <span class="math inline">\(\texttt{Model }3\)</span> – see Exercises.</p>
</section>
<section id="focus-on-regression-quiz" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="focus-on-regression-quiz">Focus on regression quiz</h2>
<p>Test your knowledge recall and application to reinforce basic ideas and prepare for similar concepts later in the module.</p>
<div class="webex-box">
<div class="webex-check">
<p>For each situation, choose one of the following statements which you think is <strong>most likely</strong> to apply.</p>
<ol type="1">
<li>Which of the following is a true statement about correlation and linear regression? (Choose any that apply.)
<div id="radio_FJOWBCVSED" class="webex-radiogroup">
<label><input type="radio" autocomplete="off" name="radio_FJOWBCVSED" value=""> <span>There is no relationship between correlation and linear regression</span></label><label><input type="radio" autocomplete="off" name="radio_FJOWBCVSED" value=""> <span>If the correlation is away from zero then a linear regression should always be used</span></label><label><input type="radio" autocomplete="off" name="radio_FJOWBCVSED" value="answer"> <span>The correlation and the regression slope parameter will have the same sign</span></label><label><input type="radio" autocomplete="off" name="radio_FJOWBCVSED" value="answer"> <span>If the correlation is close to zero then a linear regression will not be useful</span></label><label><input type="radio" autocomplete="off" name="radio_FJOWBCVSED" value=""> <span>The correlation and the slope parameter will have the opposite sign</span></label>
</div></li>
<li>Which of the following is NOT a true statement about model residuals? (Choose any that apply.)
<div id="radio_YZIZCJLWZY" class="webex-radiogroup">
<label><input type="radio" autocomplete="off" name="radio_YZIZCJLWZY" value=""> <span>Will always sum to zero</span></label><label><input type="radio" autocomplete="off" name="radio_YZIZCJLWZY" value="answer"> <span>All should be zero if the model is a good fit</span></label><label><input type="radio" autocomplete="off" name="radio_YZIZCJLWZY" value=""> <span>Can be used to judge how well the model fits the data</span></label><label><input type="radio" autocomplete="off" name="radio_YZIZCJLWZY" value=""> <span>Can help to identify unusual data points</span></label><label><input type="radio" autocomplete="off" name="radio_YZIZCJLWZY" value=""> <span>Should always be plotted as part of a data analysis</span></label>
</div></li>
<li>Which of the following is a true statement about prediction using linear regression? (Choose any that apply.)
<div id="radio_AWVOQKLBVY" class="webex-radiogroup">
<label><input type="radio" autocomplete="off" name="radio_AWVOQKLBVY" value="answer"> <span>We should be careful about extrapolating</span></label><label><input type="radio" autocomplete="off" name="radio_AWVOQKLBVY" value="answer"> <span>Interpolation and extrapolation are both types of prediction</span></label><label><input type="radio" autocomplete="off" name="radio_AWVOQKLBVY" value=""> <span>Prediction is always reliable</span></label><label><input type="radio" autocomplete="off" name="radio_AWVOQKLBVY" value=""> <span>Interpolation should only be used if we know the true relationship is linear</span></label><label><input type="radio" autocomplete="off" name="radio_AWVOQKLBVY" value="answer"> <span>Interpolation is performed using the fitted model</span></label>
</div></li>
<li>Which of the following is NOT an important part of regression model fitting? (Choose any that apply.)
<div id="radio_YQFASJMEKG" class="webex-radiogroup">
<label><input type="radio" autocomplete="off" name="radio_YQFASJMEKG" value=""> <span>The command <strong>cor</strong> to check for a relationship between variables</span></label><label><input type="radio" autocomplete="off" name="radio_YQFASJMEKG" value=""> <span>A scatter plot of the data</span></label><label><input type="radio" autocomplete="off" name="radio_YQFASJMEKG" value=""> <span>A scatter plot of the residuals</span></label><label><input type="radio" autocomplete="off" name="radio_YQFASJMEKG" value="answer"> <span>A histogram of the data</span></label><label><input type="radio" autocomplete="off" name="radio_YQFASJMEKG" value=""> <span>The command <strong>lm</strong> to fit a linear model</span></label>
</div></li>
<li>Which of the following is NOT important when performing data analysis? (Choose any that apply.)
<div id="radio_DCQBSTVBKT" class="webex-radiogroup">
<label><input type="radio" autocomplete="off" name="radio_DCQBSTVBKT" value=""> <span>Are the data representative of what we are aiming to investigate</span></label><label><input type="radio" autocomplete="off" name="radio_DCQBSTVBKT" value=""> <span>Do we need authorization from the person collecting the data before we can use it</span></label><label><input type="radio" autocomplete="off" name="radio_DCQBSTVBKT" value="answer"> <span>Background information is not needed before analyzing a new data set – it's only the numbers that matter</span></label><label><input type="radio" autocomplete="off" name="radio_DCQBSTVBKT" value=""> <span>Is the data reliable and have suitable data checks been performed</span></label><label><input type="radio" autocomplete="off" name="radio_DCQBSTVBKT" value=""> <span>The analysis should be done professionally. We must not involve our personal views to influence our analysis and conclusions</span></label>
</div></li>
</ol>
</div>
</div>
</section>
<section id="sec-typesnormalvariable" class="level2" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="sec-typesnormalvariable"><span class="header-section-number">2.3</span> Types of normal linear model</h2>
<p>Here we consider how normal linear models can be set up for different types of explanatory variable. The dependent variable <span class="math inline">\(y\)</span> is modelled as a linear combination of <span class="math inline">\(p\)</span> explanatory variables <span class="math inline">\(\mathbf{x} =(x_1, x_2,\ldots, x_p)\)</span> plus a random error <span class="math inline">\(\epsilon \sim N(0, \sigma^2)\)</span>, where ‘~’ means ‘is distributed as’. Several models are of this kind, depending on the number and type of explanatory variables. <a href="#tbl-linear_models" class="quarto-xref">Table&nbsp;<span>2.2</span></a> lists some types of normal linear models with their explanatory variable types.</p>
<div id="tbl-linear_models" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-linear_models-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2.2: Types of normal linear model and their explanatory variable types where indicator function <span class="math inline">\(I(x=j)=1\)</span> if <span class="math inline">\(x=j\)</span> and <span class="math inline">\(0\)</span> otherwise.
</figcaption>
<div aria-describedby="tbl-linear_models-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 26%">
<col style="width: 27%">
<col style="width: 45%">
</colgroup>
<tbody>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(p\)</span></td>
<td><strong>Explanatory variables</strong></td>
<td><strong>Model</strong></td>
</tr>
<tr class="even">
<td style="text-align: center;">1</td>
<td>Quantitative</td>
<td>Simple linear regression <span class="math inline">\(y=\alpha+\beta x+\epsilon\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;">&gt;1</td>
<td>Quantitative</td>
<td>Multiple linear regression<span class="math inline">\(y=\alpha+\sum_{i=1}^p\beta_i x_i+\epsilon\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;">1</td>
<td>Dichotomous (<span class="math inline">\(x=1\)</span> or <span class="math inline">\(2\)</span>)</td>
<td>Two-sample t-test <span class="math inline">\(y=\alpha+\delta ~ I(x=2)+\epsilon\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;">1</td>
<td>Polytomous, <span class="math inline">\(k\)</span> levels <span class="math inline">\((x=1,\ldots,k)\)</span></td>
<td>One-way ANOVA<span class="math inline">\(y=\alpha+\sum_{j=1}^k \delta_j \ I(x=j)+\epsilon\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;">&gt;1</td>
<td>Qualitative</td>
<td><span class="math inline">\(p\)</span>-way ANOVA</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>For the two-sample t-test model<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a>, observations in the two groups have means <span class="math inline">\(\alpha+\beta_1\)</span> and <span class="math inline">\(\alpha + \beta_2\)</span> . Notice, however, that we have three parameters with only two group sample means and hence parameter estimation is not possible. To avoid this identification problem, we either impose a ‘corner’ constraint: <span class="math inline">\(\beta_1=0\)</span> and then <span class="math inline">\(\beta_2\)</span> represents the difference in the Group 2 mean relative to a baseline of Group <span class="math inline">\(1\)</span>. Alternatively, we may impose a ‘sum-to-zero’ constraint: <span class="math inline">\(\beta_1+ \beta_2 =0\)</span>, the values <span class="math inline">\(\beta_1=-\beta_2\)</span> then give differences in the groups means relative to the overall mean. <a href="#tbl-ttest" class="quarto-xref">Table&nbsp;<span>2.3</span></a> shows the effect of the parameter constraint on the group means.</p>
<div id="tbl-ttest" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ttest-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2.3: Parameters in the two-sample t-test model after imposing parameter constraint to avoid the identification problem.
</figcaption>
<div aria-describedby="tbl-ttest-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: center;">Constraint</th>
<th style="text-align: center;">Group 1 mean</th>
<th style="text-align: center;">Group 2 mean</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(\beta_1=0\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\alpha\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\alpha+\beta_2\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="math inline">\(\beta_1+\beta_2=0\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\alpha-\beta_2\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\alpha+\beta_2\)</span></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>For the general one-way ANOVA model with <span class="math inline">\(k\)</span> groups, observations in Group <span class="math inline">\(j\)</span> have mean <span class="math inline">\(\alpha + \delta_j\)</span> , for <span class="math inline">\(j =1, \ldots, k\)</span> – that leads to <span class="math inline">\(k + 1\)</span> parameters describing <span class="math inline">\(k\)</span> group means. Again we can impose the ‘corner’ constraint: <span class="math inline">\(\delta_1 = 0\)</span> and then <span class="math inline">\(\delta_j\)</span> represents the difference in means between Group <span class="math inline">\(j\)</span> and the baseline Group <span class="math inline">\(1\)</span>. Alternatively, we may impose a ‘sum-to-zero’ constraint:<span class="math inline">\(\sum_{j=1}^k \delta_j =0\)</span> and again <span class="math inline">\((\delta_1, \delta_2,\dots,\delta_k)\)</span> then represents an individual group effect relative to the overall data mean.</p>
</section>
<section id="sec-matrix" class="level2" data-number="2.4">
<h2 data-number="2.4" class="anchored" data-anchor-id="sec-matrix"><span class="header-section-number">2.4</span> Matrix representation of linear models</h2>
<p>All of the models in Table <a href="#tbl-linear_models" class="quarto-xref">Table&nbsp;<span>2.2</span></a> can be fitted by least squares (OLS). To describe this, a matrix formulation will be most convenient:</p>
<p><span id="eq-matrix-linear-model"><span class="math display">\[
\mathbf{Y} = X\boldsymbol{\beta}+\boldsymbol{\epsilon}
\tag{2.4}\]</span></span></p>
<p>where</p>
<ul>
<li><span class="math inline">\(\mathbf{Y}\)</span> is an <span class="math inline">\(n\times 1\)</span> vector of observed response values with <span class="math inline">\(n\)</span> being the number of observations.</li>
<li><span class="math inline">\(X\)</span> is an <span class="math inline">\(n\times p\)</span> <em>design</em> matrix, to be discussed below.</li>
<li><span class="math inline">\(\boldsymbol{\beta}\)</span> is a <span class="math inline">\(p\times 1\)</span> vector of parameters or coefficients to be estimated.</li>
<li><span class="math inline">\(\boldsymbol{\epsilon}\)</span> is an <span class="math inline">\(n\times 1\)</span> vector of independent and identically distributed (IID) random variables, which here <span class="math inline">\(\epsilon \sim N(0, \sigma^2)\)</span> and is called the “error” term.</li>
</ul>
<p>Creating the design matrix is a key part of the modelling as it describes the important structure of investigation or experiment. The design matrix can be constructed by the following process.</p>
<ol type="1">
<li><p>Begin with an <span class="math inline">\(X\)</span> containing only one column: a vector of ones for the overall mean or intercept term (the <span class="math inline">\(\alpha\)</span> in <a href="#tbl-linear_models" class="quarto-xref">Table&nbsp;<span>2.2</span></a>).</p></li>
<li><p>For each explanatory variable <span class="math inline">\(x_j\)</span>, do the following:</p>
<ol type="a">
<li>If a variable <span class="math inline">\(x_j\)</span> is quantitative, add a column to <span class="math inline">\(X\)</span> containing the values of <span class="math inline">\(x_j.\)</span></li>
<li>If <span class="math inline">\(x_j\)</span> is qualitative with <span class="math inline">\(k\)</span> levels, add <span class="math inline">\(k\)</span> “dummy” columns to <span class="math inline">\(X\)</span>, taking values 0 and 1, where a 1 in the <span class="math inline">\(\ell\)</span>th dummy column identifies that the corresponding observation is at level <span class="math inline">\(\ell\)</span> of factor <span class="math inline">\(x_j\)</span> . For example, suppose we have a factor <span class="math inline">\(\mathbf{x}_j = (M, M, F, M, F)\)</span> representing the sex of <span class="math inline">\(n = 5\)</span> individuals. This information can be coded into two dummy columns of <span class="math inline">\(X\)</span>:</li>
</ol>
<p><span class="math display">\[
\begin{matrix}
\begin{matrix}
F &amp; M
\end{matrix}\\
\begin{bmatrix}
0 &amp; 1 \\
0 &amp; 1 \\
1 &amp; 0 \\
0 &amp; 1 \\
1 &amp; 0
\end{bmatrix}
\end{matrix}
\]</span></p></li>
<li><p>When qualitative variables are present, <span class="math inline">\(X\)</span> will be singular – that is, there will be linear dependencies between the columns of <span class="math inline">\(X\)</span>. For example, the sum of the two columns above is a vector of ones, the same as the intercept column. We resolve this identification problem by deleting some columns of <span class="math inline">\(X\)</span>. This is equivalent to applying the corner constraint <span class="math inline">\(\delta_1 = 0\)</span> in the one-way ANOVA.</p>
<p>In the above example, after removing a column, we get:<br>
<span class="math display">\[
\mathbf{X}=\begin{bmatrix}
1 &amp;  1 \\
1 &amp;  1 \\
1 &amp;  0 \\
1 &amp;  1 \\
1 &amp;  0
\end{bmatrix}.
\]</span></p></li>
<li><p>Each column of <span class="math inline">\(X\)</span> represents either a quantitative variable, or a level of a qualitative variable. We will use <span class="math inline">\(i = 1, \ldots, n\)</span> to label the observations (rows of <span class="math inline">\(X\)</span>) and <span class="math inline">\(j = 1, \ldots, p\)</span> to label the columns of <span class="math inline">\(X\)</span>.</p></li>
</ol>
<p><br>
</p>
<p><strong>Example: Simple linear regression</strong></p>
<p>Consider the simple linear regression model <span class="math inline">\(y=\alpha+\beta x+\epsilon\)</span> with <span class="math inline">\(\epsilon \sim N(0, \sigma^2)\)</span>. Given data on <span class="math inline">\(n\)</span> pairs <span class="math inline">\((x_i, y_i), i = 1, \ldots, n\)</span>, we write this as</p>
<p><span id="eq-linear-data"><span class="math display">\[
y_i = \alpha+\beta x_i+\epsilon_i, \quad \text{for } i=1,2,\dots,n,
\tag{2.5}\]</span></span></p>
<p>where the <span class="math inline">\(\epsilon_i\)</span> are IID <span class="math inline">\(N(0,\sigma^2)\)</span>. In matrix form, this becomes</p>
<p><span id="eq-simple-linear"><span class="math display">\[
\mathbf{Y}=X\boldsymbol{\beta}+\boldsymbol{\epsilon}
\tag{2.6}\]</span></span> with <span class="math display">\[
\mathbf{Y}=\begin{bmatrix}
y_1\\
\vdots\\
y_n
\end{bmatrix},
%
\hspace{5mm}
%
X=\begin{bmatrix}
1 &amp; x_1\\
\vdots &amp; \vdots\\
1 &amp; x_n
\end{bmatrix},
%
\hspace{5mm}
%
\boldsymbol{\beta}=
\begin{bmatrix}
\beta_1\\
\beta_2
\end{bmatrix}
=
\begin{bmatrix}
\alpha\\
\beta
\end{bmatrix},
%
\hspace{5mm}
%
\boldsymbol{\epsilon}=
\begin{bmatrix}
\epsilon_1\\
\vdots\\
\epsilon_n
\end{bmatrix}.
\]</span> The <span class="math inline">\(i\)</span>th row of <a href="#eq-simple-linear" class="quarto-xref">Equation&nbsp;<span>2.6</span></a> has the same meaning as <a href="#eq-linear-data" class="quarto-xref">Equation&nbsp;<span>2.5</span></a>: <span class="math display">\[
y_i = 1\times \beta_1 + x_i\times \beta_2 +\epsilon_i = \alpha+\beta x_i +\epsilon_i,  \hspace{2mm} \text{for } i=1,2,\dots,n.
\]</span><br>
</p>
<p><strong>Example: One-way ANOVA</strong></p>
<p>For one-way ANOVA with <span class="math inline">\(k\)</span> levels, the model is <span class="math display">\[
y_i =\alpha+\sum_{j=1}^k \delta_j \ I(x_i=j)+\epsilon_i, \quad \text{for } i=1, 2, \dots,n,
\]</span> where <span class="math inline">\(x_i\)</span> denotes the group level of individual <span class="math inline">\(i\)</span>. So if <span class="math inline">\(y_i\)</span> is from the <span class="math inline">\(j\)</span>th group then <span class="math inline">\(y_i \sim N(\alpha+\delta_j, \sigma^2)\)</span>. Here <span class="math inline">\(\alpha\)</span> is the intercept and the <span class="math inline">\((\delta_1, \delta_2, \dots,\delta_k)\)</span> represent the “main effects”.</p>
<p>We can store the information about the levels of <span class="math inline">\(g\)</span> in a dummy matrix <span class="math inline">\(X^* = (x^*_{ij})\)</span> where</p>
<p><span class="math display">\[
x^*_{ij} = \left\{
\begin{array}{cl}
1, &amp; g_i=j,\\
0, &amp; \text{otherwise.}
\end{array}
\right.
\]</span></p>
<p>Then set <span class="math inline">\(X = [1, X^*]\)</span>, where <span class="math inline">\(1\)</span> is an <span class="math inline">\(n\)</span>-vector of <span class="math inline">\(1\)</span>’s. For the male–female example at (1.12), we have <span class="math inline">\(n = 5\)</span> and a sex factor:</p>
<p><span class="math display">\[
g=\begin{bmatrix}1\\ 1 \\2\\1\\2\end{bmatrix},
%
\hspace{5mm}
%
X=\begin{bmatrix}
1 &amp; 1 &amp; 0\\
1&amp;1&amp; 0 \\ 1&amp; 0 &amp; 1\\ 1&amp; 1 &amp; 0 \\ 1&amp; 0 &amp; 1
\end{bmatrix},
%
\hspace{5mm}
%
\beta=\begin{bmatrix}\beta_1\\\beta_2\\\beta_3\end{bmatrix}
=\begin{bmatrix}\alpha\\\delta_1 \\\delta_2\end{bmatrix}.
\]</span></p>
<p>Then the <span class="math inline">\(i\)</span>th row of <span class="math inline">\(X\)</span> becomes <span class="math inline">\(\beta_1 + \beta_2 = \alpha + \delta_1\)</span> if <span class="math inline">\(g_i = 1\)</span> and <span class="math inline">\(\beta_1 + \beta_3 = \alpha + \delta_2\)</span> if <span class="math inline">\(g_i\)</span> = 2. That is, the <span class="math inline">\(i\)</span>th row of <span class="math inline">\(X\)</span> is</p>
<p><span class="math display">\[
\alpha+\sum_{j=1}^2 \delta_j I(g_i=j)
\]</span> so this model can be written <span class="math inline">\(Y=X\beta+\epsilon\)</span>. Here, <span class="math inline">\(X\)</span> is singular: its last two columns added together equal its first column. Statistically, the problem is that we are trying to estimate two means (the mean response for Boys and the mean response for Girls) with three parameters (<span class="math inline">\(\alpha\)</span>, <span class="math inline">\(\delta_2\)</span> and <span class="math inline">\(\delta_2\)</span>).</p>
<p>In practice, we often resolve this aliasing or identification problem by setting one of the parameters to be zero, that is <span class="math inline">\(\delta_1 = 0\)</span>, which corresponds to deleting the second column of <span class="math inline">\(X\)</span>).</p>
</section>
<section id="focus-on-matrix-representations-quiz" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="focus-on-matrix-representations-quiz">Focus on matrix representations quiz</h2>
<div class="webex-box">
<div class="webex-check">
<p>For each situation, choose one of the following statements which you think is <strong>most likely</strong> to apply.</p>
<ol type="1">
<li><p>What is the dimension of the design matrix? <select class="webex-select"><option value="blank"></option><option value="">2</option><option value="">p by 1</option><option value="answer">n by p</option><option value="">n by 1</option><option value="">X</option></select></p></li>
<li><p>What is the distribution of the error term? <select class="webex-select"><option value="blank"></option><option value="answer">normal</option><option value="">n by 1</option><option value="">mean zero</option><option value="">IDD</option><option value="">random variable</option></select></p></li>
<li><p>Which quantity represents the model parameters? <select class="webex-select"><option value="blank"></option><option value="">X</option><option value="">epsilon</option><option value="">Y</option><option value="">n</option><option value="answer">beta</option></select></p></li>
<li><p>Which two terms in the model have the same dimensions? <select class="webex-select"><option value="blank"></option><option value="">beta and epsilon</option><option value="">Y and beta</option><option value="">Y and X</option><option value="">X and beta</option><option value="answer">Y and epsilon</option></select></p></li>
<li><p>Which of the following is a potential problem when using qualitative variables? <select class="webex-select"><option value="blank"></option><option value="">X is full rank</option><option value="">X can be zero</option><option value="">X is not square</option><option value="answer">X is singular</option><option value="">X can be negative</option></select></p></li>
</ol>
</div>
</div>
</section>
<section id="sec-shorthand" class="level2" data-number="2.5">
<h2 data-number="2.5" class="anchored" data-anchor-id="sec-shorthand"><span class="header-section-number">2.5</span> Model shorthand notation</h2>
<p>In R, a qualitative (categorical) variable is called a <em>factor</em>, and its categories are called <em>levels</em>. For example, variable <span class="math inline">\(\texttt{Sex}\)</span> in the birth weight data (above) has levels coded “M” for ‘Boy’ and “F” for ‘Girl’. It may not be obvious to <strong>R</strong> whether a variable is quantitative or qualitative. For example, a qualitative variable called <span class="math inline">\(\texttt{Grade}\)</span> might have categories 1, 2 and 3. If was included in a model, R would treat it as quantitative unless we declare it to be a factor, which we can do with the command:</p>
<p><span class="math inline">\(\texttt{grade = as.factor(grade)}\)</span></p>
<p>A convenient model-specification notation has been developed from which the design matrix <span class="math inline">\(X\)</span> can be constructed. Below, <span class="math inline">\(E, F, \ldots\)</span> denote generic quantitative (continuous) or qualitative (categorical) variables. Terms in this notation may take the following forms:</p>
<ol type="a">
<li><p><span class="math inline">\(1\)</span> : a column of 1’s to accommodate an intercept term (the <span class="math inline">\(\alpha\)</span>’s of <a href="#tbl-linear_models" class="quarto-xref">Table&nbsp;<span>2.2</span></a> ). This is included in the model by default.</p></li>
<li><p><span class="math inline">\(E\)</span> : variable <span class="math inline">\(E\)</span> is included in the model. The design matrix includes <span class="math inline">\(k_E\)</span> columns for <span class="math inline">\(E\)</span>. If <span class="math inline">\(E\)</span> is quantitative, <span class="math inline">\(k_E = 1\)</span>. If E is qualitative, <span class="math inline">\(k_E\)</span> is the number of levels of <span class="math inline">\(E\)</span> minus 1.</p></li>
<li><p><span class="math inline">\(E +F\)</span> : both <span class="math inline">\(E\)</span> and <span class="math inline">\(F\)</span> are included the model. The design matrix includes <span class="math inline">\(k_E +k_F\)</span> columns accordingly.</p></li>
<li><p><span class="math inline">\(E : F\)</span> (sometimes <span class="math inline">\(E \cdot F\)</span>) : the model includes an interaction between <span class="math inline">\(E\)</span> and <span class="math inline">\(F\)</span>; each column that would be included for <span class="math inline">\(E\)</span> is multiplied by each column for <span class="math inline">\(F\)</span> in turn. The design matrix includes <span class="math inline">\(k_E \times k_F\)</span> columns accordingly.</p></li>
<li><p><span class="math inline">\(E * F\)</span> : shorthand for <span class="math inline">\(1 + E + F + E : F\)</span>: useful for crossed models where <span class="math inline">\(E\)</span> and <span class="math inline">\(F\)</span> are different factors. For example, <span class="math inline">\(E\)</span> labels age groups; <span class="math inline">\(F\)</span> labels medical conditions.</p></li>
<li><p><span class="math inline">\(E/F\)</span> : shorthand for <span class="math inline">\(1 + E + E : F\)</span>: useful for nested models where <span class="math inline">\(F\)</span> is a factor whose levels have meaning only within levels of factor <span class="math inline">\(E\)</span>. For example, <span class="math inline">\(E\)</span> labels different hospitals; <span class="math inline">\(F\)</span> labels wards within hospitals.</p></li>
<li><p><span class="math inline">\(\text{poly}(E; \ell)\)</span> : shorthand for an orthogonal polynomial, wherein <span class="math inline">\(x\)</span> contains a set of mutually orthogonal columns containing polynomials in <span class="math inline">\(E\)</span> of increasing order, from order <span class="math inline">\(1\)</span> through order <span class="math inline">\(\ell\)</span>.</p></li>
<li><p><span class="math inline">\(-E\)</span> : shorthand for removing a term from the model; for example <span class="math inline">\(E * F -E\)</span> is short for <span class="math inline">\(1 + F + E : F\)</span>.</p></li>
<li><p><span class="math inline">\(I()\)</span> : shorthand for an arithmetical expression (not to be confused with the indicator function defined above). For example, <span class="math inline">\(I(E + F)\)</span> denotes a new quantitative variable constructed by adding together quantitative variables <span class="math inline">\(E\)</span> and <span class="math inline">\(F\)</span>. This would cause an error if either <span class="math inline">\(E\)</span> or <span class="math inline">\(F\)</span> has been declared as a factor. What would happen in this example if we omitted the <span class="math inline">\(I(\cdot)\)</span> notation?</p></li>
</ol>
<p>The notation uses “~” as shorthand for “is modelled by” or “is regressed on”. For example,</p>
<ul>
<li><p>Weight is regressed on age-group and sex with no interaction between them: <span class="math display">\[
\texttt{Weight} \sim \texttt{Age} + \texttt{Sex}
\]</span> as for the birthweight data in Figure 1.2c.</p></li>
<li><p>Well being is regressed on age-group and income-group, where income is thought to affect wellbeing differentially by age: <span class="math display">\[
\texttt{Wellbeing} \sim \texttt{Age} * \texttt{Income}
\]</span></p></li>
<li><p>Class of degree is regressed on school of the university and on degree subject within the school: <span class="math display">\[
\texttt{DegreeClass} \sim \texttt{School/Subject}
\]</span></p></li>
<li><p>Yield of wheat is regressed on seed-variety and annual rainfall: <span class="math display">\[
\texttt{Yield} \sim \texttt{Variety} + \texttt{poly}(\texttt{Rainfall}, 2)
\]</span></p></li>
<li><p>Profit is regressed on amount invested: <span class="math display">\[
\texttt{Profit}\sim \texttt{Investment}- 1
\]</span> (no intercept term, that is a regression through the origin).</p></li>
</ul>
</section>
<section id="focus-on-model-notation-quiz" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="focus-on-model-notation-quiz">Focus on model notation quiz</h2>
<div class="webex-box">
<div class="webex-check">
<p>For each situation, choose one of the following statements which you think is <strong>most likely</strong> to apply.</p>
<ol type="1">
<li><p>What <strong>R</strong> command can be used to covert numerical values into a nominal variable? <select class="webex-select"><option value="blank"></option><option value="answer">as.factor</option><option value="">as.nominal</option><option value="">as.ordinal</option><option value="">as.numerical</option><option value="">factorial</option></select></p></li>
<li><p>Which of the following defines a model where variable Y is regressed on variables V1 and V2, but without an interaction? <select class="webex-select"><option value="blank"></option><option value="answer">Y ~ V1 + V2</option><option value="">V1 + V2 ~ Y</option><option value="">Y ~ V1:V2</option><option value="">Y ~ V1 + V2 + V1:V2</option><option value="">Y ~ V1*V2</option></select></p></li>
<li><p>Which of the following defines a model where variable Y is regressed on variables V1 and V2, including a constant and an interaction? <select class="webex-select"><option value="blank"></option><option value="">Y ~ 1+V1:V2</option><option value="answer">Y ~ V1*V2</option><option value="">Y ~ 1 + V1 + V2</option><option value="">Y ~ V1 + V2 + V1:V2 -1</option><option value="">Y ~ 1+V1/V2</option></select></p></li>
<li><p>Which of the following defines a model regression Y on the product of V1 and V2? <select class="webex-select"><option value="blank"></option><option value="">Y ~ V1:V2</option><option value="">Y ~ I(V1 + V2)</option><option value="">Y ~ V1.V2</option><option value="">Y ~ poly(V1,V2)</option><option value="answer">Y ~ I(V1*V2)</option></select></p></li>
<li><p>Which of the following defines a model where variable Y is regressed on a second-order polynomial in V1? <select class="webex-select"><option value="blank"></option><option value="answer">Y ~ poly(V1,2)</option><option value="">Y ~ V1*V1</option><option value="">Y ~ 1+V1</option><option value="">Y ~ I(V1)</option><option value="">Y ~ V1^2</option></select></p></li>
</ol>
</div>
</div>
</section>
<section id="fitting-linear-models-in-r" class="level2" data-number="2.6">
<h2 data-number="2.6" class="anchored" data-anchor-id="fitting-linear-models-in-r"><span class="header-section-number">2.6</span> Fitting linear models in <strong>R</strong></h2>
<p>A commonly used command for fitting a linear model in <strong>R</strong> is<span class="math display">\[\texttt{lm(formula)}.\]</span></p>
<p>Let <span class="math inline">\(\texttt{x,y,z,a,b} \dots\)</span> represent <strong>R</strong> vectors, all of the same length <span class="math inline">\(n\)</span> (perhaps read in from a data file using the <span class="math inline">\(\texttt{read.table}\)</span> and <span class="math inline">\(\texttt{attach}\)</span> commands).<br>
If <span class="math inline">\(\texttt{a,b}\)</span> are qualitative variables, then they first need to be declared as factors by <span class="math inline">\(\texttt{a = as.factor(a)}\)</span>, etc.</p>
<p>The <span class="math inline">\(\texttt{formula}\)</span> argument of <span class="math inline">\(\texttt{lm}\)</span> specifies the required model in compact notation, e.g.&nbsp;<span class="math inline">\(\texttt{y} \sim \texttt{x+z}\)</span> or <span class="math inline">\(\texttt{y} \sim \texttt{x + z*a}\)</span> where <span class="math inline">\(\sim, \texttt{+,*}\)</span> have the same meaning as in <a href="#sec-shorthand" class="quarto-xref"><span>Section 2.5</span></a>.</p>
<p>To extract information about a fitted linear model, it is best to store the result of <span class="math inline">\(\texttt{lm}\)</span> as a variable and then to use the following functions:</p>
<ul>
<li>To fit a linear model and store the result in <span class="math inline">\(\texttt{my.lm}\)</span> (for example):<br>
<span class="math inline">\(\texttt{my.lm = lm(y}\sim\texttt{x + a*b})\)</span></li>
<li>To print various pieces of information including deviance residuals, parameter estimates and standard errors, deviances, and (if specified) correlations of parameter estimates:<br>
<span class="math inline">\(\texttt{summary(my.lm, correlation=T)}\)</span></li>
<li>To print the anova table of the fitted model:<br>
<span class="math inline">\(\texttt{anova(my.lm)}\)</span></li>
<li>To print the residual degrees of freedom of the fitted model:<br>
<span class="math inline">\(\texttt{df.residual(my.lm)}\)</span></li>
<li>To print the vector of fitted values under the fitted model:<br>
<span class="math inline">\(\texttt{fitted.values(my.lm)}\)</span></li>
<li>To print the residuals from the fitted model:<br>
<span class="math inline">\(\texttt{residuals(my.lm)}\)</span><br>
</li>
<li>To print the parameter estimates from the fitted model:<br>
<span class="math inline">\(\texttt{coefficients(my.lm)}\)</span></li>
<li>To print the design matrix for a specified model formula: <span class="math inline">\(\texttt{model.matrix(y}\sim\texttt{a*b)}\)</span></li>
</ul>
<p>The functions <span class="math inline">\(\texttt{summary}\)</span>, <span class="math inline">\(\texttt{anova}\)</span>, and possibly <span class="math inline">\(\texttt{model.matrix}\)</span> are the most useful for printing out information about the fitted model. The results of the other functions can be saved as variables for further computation. In particular, you should look for an ansence of structure in a plot the residuals and you may need to make predictions of the response variable for new values of the explanatory variable.</p>
<p><strong>Example of fitting a linear model in R</strong></p>
<p>Here is a toy example of <strong>R</strong> commands for modelling a response in terms of one quantitative explanatory variable.</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">273686</span>) <span class="co"># for reproducibility</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Create some artificial data</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>x <span class="ot">=</span> <span class="fu">seq</span>(<span class="dv">1</span>,<span class="dv">12</span>, <span class="at">length.out=</span><span class="dv">50</span>)</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>y <span class="ot">=</span> <span class="dv">2</span> <span class="sc">+</span> <span class="fl">0.2</span><span class="sc">*</span>x <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="fu">length</span>(x),<span class="dv">0</span>,<span class="fl">0.2</span>)</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit the linear model</span></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>my.lm <span class="ot">=</span> <span class="fu">lm</span>(y <span class="sc">~</span> x)</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Show summary information of the fitted model</span></span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(my.lm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = y ~ x)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.38790 -0.12026 -0.01578  0.12751  0.44184 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 1.941552   0.062524   31.05   &lt;2e-16 ***
x           0.204299   0.008609   23.73   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.1972 on 48 degrees of freedom
Multiple R-squared:  0.9215,    Adjusted R-squared:  0.9198 
F-statistic: 563.1 on 1 and 48 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<div class="cell" data-layout="[[1,1]]">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Adjust plot layout</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mar=</span><span class="fu">c</span>(<span class="dv">4</span>,<span class="dv">4</span>,<span class="dv">1</span>,<span class="dv">1</span>))</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot data and add the fitted regression line</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(y<span class="sc">~</span>x, <span class="at">pch=</span><span class="dv">16</span>)</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(my.lm)</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the std dev of the residuals</span></span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>resid.sd <span class="ot">=</span> <span class="fu">sd</span>(my.lm<span class="sc">$</span>residuals)</span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the residuals against the fitted values</span></span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(my.lm<span class="sc">$</span>fitted.values, my.lm<span class="sc">$</span>residuals, <span class="at">pch=</span><span class="dv">16</span>,</span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab=</span><span class="st">"Fitted values"</span>, <span class="at">ylab=</span><span class="st">"Residuals"</span>,</span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylim=</span> <span class="fl">0.6</span><span class="sc">*</span><span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>, <span class="dv">1</span>))</span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Add zero line and lines =/- 2sd</span></span>
<span id="cb15-17"><a href="#cb15-17" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="dv">0</span>, <span class="at">lty=</span><span class="dv">2</span>)</span>
<span id="cb15-18"><a href="#cb15-18" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="dv">2</span><span class="sc">*</span>resid.sd<span class="sc">*</span><span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>, <span class="dv">1</span>), <span class="at">lty=</span><span class="dv">2</span>, <span class="at">col=</span><span class="st">"red"</span>)</span>
<span id="cb15-19"><a href="#cb15-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-20"><a href="#cb15-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Look at distribution of residuals</span></span>
<span id="cb15-21"><a href="#cb15-21" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(my.lm<span class="sc">$</span>residuals, <span class="at">probability=</span>T, </span>
<span id="cb15-22"><a href="#cb15-22" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlim=</span><span class="fl">0.6</span><span class="sc">*</span><span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>, <span class="dv">1</span>), <span class="at">main=</span><span class="st">""</span>)</span>
<span id="cb15-23"><a href="#cb15-23" aria-hidden="true" tabindex="-1"></a><span class="co"># Compare residuals with normal distribution</span></span>
<span id="cb15-24"><a href="#cb15-24" aria-hidden="true" tabindex="-1"></a><span class="fu">qqnorm</span>(my.lm<span class="sc">$</span>residuals, <span class="at">main=</span><span class="st">""</span>); <span class="fu">qqline</span>(my.lm<span class="sc">$</span>residuals)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div id="fig-toy" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-toy-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-toy" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-toy-1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-toy-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="2_linearmodels_files/figure-html/fig-toy-1.png" class="img-fluid figure-img" data-ref-parent="fig-toy" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-toy-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) Data and fitted model
</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-toy" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-toy-2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-toy-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="2_linearmodels_files/figure-html/fig-toy-2.png" class="img-fluid figure-img" data-ref-parent="fig-toy" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-toy-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b) Residual plot
</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-toy" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-toy-3" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-toy-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="2_linearmodels_files/figure-html/fig-toy-3.png" class="img-fluid figure-img" data-ref-parent="fig-toy" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-toy-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(c) Histogram of residuals
</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-toy" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-toy-4" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-toy-4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="2_linearmodels_files/figure-html/fig-toy-4.png" class="img-fluid figure-img" data-ref-parent="fig-toy" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-toy-4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(d) Normal distribution QQ plot
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-toy-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2.5: Illustration of model fitting on a toy example
</figcaption>
</figure>
</div>
</div>
<p>A scatter plot of the data indicates that a linear model would be appropriate and the resulting fitted linear regression describes the data well. A residual plot shows that all residuals are within two standard deviations of zero, with the histogram showing a symmetric distribution and a QQ plot supporting normality of the residuals. All these diagnostic plots support that the model fits well.</p>
<p>Finally, we may wish to predict values of the response variable at new values of the response variable, for example at <span class="math inline">\(x=4\)</span> and <span class="math inline">\(x=6\)</span> – notice that the values of the explanatory variable must be converted into a <strong>R</strong> <span class="math inline">\(\texttt{data.frame}\)</span>:</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Use the fitted model for prediction, at say x=4 and x=6</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(my.lm, <span class="fu">data.frame</span>(<span class="at">x=</span><span class="fu">c</span>(<span class="dv">4</span>,<span class="dv">6</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>       1        2 
2.758747 3.167345 </code></pre>
</div>
</div>
</section>
<section id="ethics-in-statistics-and-data-science" class="level2" data-number="2.7">
<h2 data-number="2.7" class="anchored" data-anchor-id="ethics-in-statistics-and-data-science"><span class="header-section-number">2.7</span> Ethics in statistics and data science</h2>
<p>A brief introduction to ethics and their relevance to statistics and data science.</p>
<p>In previous module you have already seen that professional and ethical consideration are important. Whether that be when we choose which graph to present or what action to take when data is missing or how to deal with suspected outliers. It is important for statisticians and data scientists to be aware of the ethical dimensions of their work and to be able to think these through.</p>
<p>Please note that the following was produce with the help of Dr Robbie Morgan from the Interdisciplinary Applied Ethics (IDEA) Centre at the University of Leeds.</p>
<p>Roughly speaking, ethics concerns what we ought to do (should do) and the kind of person that we ought to be. Of course, we’re particularly interested in the kinds of ethical questions and challenges that you will encounter in your work as data scientists, such as:</p>
<ul>
<li>How should we collect data in a way that respects participants?</li>
<li>Why is privacy important? How should data scientists protect privacy?</li>
<li>How can algorithmic bias wrong members of the public? How should data scientists respond to this?</li>
<li>To what extent are data scientists responsible for the impact of their work?</li>
<li>When and how should data scientists challenge authority in the workplace?</li>
</ul>
<p>The work that you do as data scientists can be hugely beneficial; it develops solutions for pressing real-world problems, enables organisations to carry out important functions more effectively and efficiently, and can improve the well being of the public by enacting innovation and technological advancement. At the same time, work in data science presents risk of significant harm and injustice. Widespread data collection threatens the privacy and safety of data subjects. Facial recognition and other surveillance technologies are the latest site of long-running debates over the values of privacy and freedom versus security. Biased algorithms can inflict injustices and exacerbate entrenched inequality. Automation can cause unemployment and instability, with unpredictable results as it affects ever more areas of our lives. So, it is very important to be clear about the obligations and responsibilities that data scientists have to their employers, colleagues, and, most importantly, to society as a whole.</p>
<p>Please keep these issues in mind throughout any data analysis and modelling work, especially if you follow such a career path after graduation.</p>
</section>
<section id="exercises" class="level2" data-number="2.8">
<h2 data-number="2.8" class="anchored" data-anchor-id="exercises"><span class="header-section-number">2.8</span> Exercises</h2>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>Unless otherwise stated, data files will be available online at: richardpmann.com/MATH3823/Datasets/<em>filename.ext</em>, where <em>filename.ext</em> is the stated filename with extension.</p>
</div>
</div>
<div class="webex-box">
2.1. For each situation, consider the data description, correlation value, and data visualization. Then, identify whether the variables are related and if a linear model would be suitable.
<div class="webex-solution">
<button>
Click here to see hints.
</button>
<p>For each description, think about what you expect to see and then confirm this, or otherwise, with the scatter plot. Does a linear relationship seem appropriate? Also, does variation in the scatter plot and correlation value suggest a strong relationship.</p>
</div>
<ol type="a">
<li>Childhood obesity is a serious medical condition which can lead to long-term health problems. A mixed-sex secondary school for ages 11-18 measures height and weight of all its new students (mostly aged 11 years old) on the first day of term and calculates their body mass index (BMI) and the average daily calorie intake was recorded. The correlation between calorie intake and BMI was 0.6 with the data shown in the scatter plot.</li>
</ol>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="2_linearmodels_files/figure-html/unnamed-chunk-30-1.png" class="img-fluid figure-img" style="width:70.0%"></p>
</figure>
</div>
</div>
</div>
<ol start="2" type="a">
<li>Domestic UK “smart meters” aim to record cumulative electricity and gas usage once per day. They use a wireless internet connection to transmit information to the energy providers, but they do not save previous values. The central system records readings as they are received and calculates the difference between successive readings. The scatter plot shows the daily electricity and gas consumption of a typical house collected using an automatic smart meter. The correlation between electricity and gas consumption is 0.4.</li>
</ol>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="2_linearmodels_files/figure-html/unnamed-chunk-31-1.png" class="img-fluid figure-img" style="width:70.0%"></p>
</figure>
</div>
</div>
</div>
<ol start="3" type="a">
<li>To investigate the punctuality of trains at Leeds City Station, a platform attendant records the number of minutes late, or early, that each train arrives at a particular platform relative to the timetable. The journey distance of each train arriving was later determined and recorded. The scatter plot shows the Distance Traveled, in miles, and the Delay, in minutes with a correlation of 0.1.</li>
</ol>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="2_linearmodels_files/figure-html/unnamed-chunk-32-1.png" class="img-fluid figure-img" style="width:70.0%"></p>
</figure>
</div>
</div>
</div>
<ol start="4" type="a">
<li>The 2022-23 UK Housing Survey, included questions regarding household income and the number of rooms. The data are shown in a scatter plot with a correlation of 0.7 between the variables.</li>
</ol>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="2_linearmodels_files/figure-html/unnamed-chunk-33-1.png" class="img-fluid figure-img" style="width:70.0%"></p>
</figure>
</div>
</div>
</div>
2.2. An extra model which could have been considered for the Birth weight data example would be one that says that <span class="math inline">\(\texttt{Weight}\)</span> is different for girls and boys, but does not depend on gestational age. Investigate this model.
<div class="webex-solution">
<button>
Click here to see hints.
</button>
<p>Write down the equation corresponding to this model. Then, load the birth weight data into RStudio and fit the model. How are the fitted model parameters related to the overall birth weight mean and the mean birth weights of the girls and boys? Is this a good fit to the data? Is Sex statistically significant?</p>
</div>
2.3. For each given situation, consider the description and then investigate the suitability of a linear model.
<div class="webex-solution">
<button>
Click here to see hints.
</button>
<p>For each given data set, produce an appropriate graph within RStudio, fit a linear regression model and add the fitted model to the graph. Comment on the quality of fit.</p>
</div>
<ol type="a">
<li>Continuing the childhood obesity example, use the data in file <em>schoolstudy.csv</em> to model the relationship between BMI and calorie intake in 11-year old children.&nbsp;<br>
</li>
<li>To study the profitability of several iron ore (hematite) extraction quarries, small samples are taken from lorries arriving at an iron purification site. The lorries are open-topped with most travelling less than 20 Km but one quarry is more than 100 Km away. A chemical analysis provides a percentage of pure iron in the sample. Quarries with iron content less than 30% are not considered economically viable. The data file <em>iron.csv</em> contains measurements of percentage pure iron arriving at an iron purification site recorded over a 50 year period. Model the relationship between iron purity and time.<br>
</li>
<li>A study aims to investigate osteoporosis in women before and after menopause. The X-rays of a randomly selected sample of patients taking routine mammograms are analysed. The age of the patient and their menopause status are recorded, along with a measure of bone density calculated from the X-ray. Use the data in the file <em>bmd.csv</em> to model the relationship between age and Tscore, noting that a value of below -2.5 indicates osteoperosis, between -2.5 and -1.0 indicates osteopenia whereas above -1.0 is normal.<br>
</li>
<li>A primary school head teaching wishes to investigate the relationship between social skills of children and the ages of their brothers and sisters. The hypothesis is that those with older siblings will be better able to deal with social interaction. The file <em>siblings.csv</em> contains data on the age of the eldest sibling of a class of 6-year old school children along with a <em>social skills</em> score for each child assessed during the school lunch break. Model the relationship between sibling age and social skills.</li>
</ol>
<p>2.4. In an experiment to investigate Ohm’s Law, <span class="math inline">\(V=IR\)</span> where <span class="math inline">\(V\)</span> is Voltage, I is current and <span class="math inline">\(R\)</span> is resistance of the material, the following data<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a> were recorded:</p>
<div id="tbl-ohmslawdata" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ohmslawdata-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2.4: Experimental verification of Ohm’s Law
</figcaption>
<div aria-describedby="tbl-ohmslawdata-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<tbody>
<tr class="odd">
<td>Voltage (Volts)</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">8</td>
<td style="text-align: center;">10</td>
<td style="text-align: center;">12</td>
<td style="text-align: center;">14</td>
<td style="text-align: center;">18</td>
<td style="text-align: center;">20</td>
<td style="text-align: center;">24</td>
</tr>
<tr class="even">
<td>Current (mAmps)</td>
<td style="text-align: center;">11</td>
<td style="text-align: center;">24</td>
<td style="text-align: center;">30</td>
<td style="text-align: center;">36</td>
<td style="text-align: center;">40</td>
<td style="text-align: center;">53</td>
<td style="text-align: center;">58.5</td>
<td style="text-align: center;">70</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
Does this data support Ohm’s Law? What is the resistance of the material used?
<div class="webex-solution">
<button>
Click here to see hints.
</button>
<p>There is no data file prepared for this and so create your own variables, then perform a linear regression. Comment on the quality of fit. Note that Ohm’s Law is a linear function but without intercept and that the resistance is a constant multiplying the current.</p>
</div>
<p>2.5 In an investigation<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a> into the effect of eating on pulse rate, 6 men and 6 women were tested before and after a meal, with the following results:</p>
<div id="tbl-pulserate" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-pulserate-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2.5: At rest pulse rate before and after a meal for men and women
</figcaption>
<div aria-describedby="tbl-pulserate-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<tbody>
<tr class="odd">
<td>Men</td>
<td>before</td>
<td style="text-align: right;">105</td>
<td style="text-align: right;">79</td>
<td style="text-align: right;">79</td>
<td style="text-align: right;">103</td>
<td style="text-align: right;">87</td>
<td style="text-align: right;">97</td>
</tr>
<tr class="even">
<td></td>
<td>after</td>
<td style="text-align: right;">109</td>
<td style="text-align: right;">87</td>
<td style="text-align: right;">86</td>
<td style="text-align: right;">109</td>
<td style="text-align: right;">100</td>
<td style="text-align: right;">101</td>
</tr>
<tr class="odd">
<td>Women</td>
<td>before</td>
<td style="text-align: right;">74</td>
<td style="text-align: right;">73</td>
<td style="text-align: right;">82</td>
<td style="text-align: right;">78</td>
<td style="text-align: right;">86</td>
<td style="text-align: right;">77</td>
</tr>
<tr class="even">
<td></td>
<td>after</td>
<td style="text-align: right;">82</td>
<td style="text-align: right;">80</td>
<td style="text-align: right;">90</td>
<td style="text-align: right;">90</td>
<td style="text-align: right;">93</td>
<td style="text-align: right;">81</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Suggest a suitable model for this situation and write down the corresponding design matrix. Calculate the parameter estimates using the matrix regression estimation equation.</p>
Perform an appropriate analysis in R to find out if there is evidence to suggest that the change in pulse rate due to a meal is the same for men and women.
<div class="webex-solution">
<button>
Click here to see hints.
</button>
<p>Beware! This time we have categorical variables: “before”/“after” and “Men/Women”. To create the design matrix think of writing down the terms needed to produce each data value and don’t forget to remove columns to make the solution identifiable. Also, don’t do the matrix multiplication/inversion by hand but use R to solve the matrix calculation. If the change in pulse rate is different for men and women then the interaction should be significant.</p>
</div>
<p>2.6 A laboratory experiment<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a> was performed into the effect of seasonal floods on the growth of barley seedlings in a incubator, as measured by their height in mm. Three types of barley seed (Goldmarker, Midas, Igri) were used with two watering condition (Normal and Waterlogged). Further, each combination was repeated four times on different shelves in the laboratory incubator (Top, Second, Third and Bottom shelf). The data are available in the file barley.csv</p>
<p>Suggest a suitable model for this situation. Identify the response and explanatory variables and list the levels for any qualitative variables. Write down the design matrix for each model you consider.</p>
<p>Perform appropriate analyses to test if each of the following are important: (a) watering condition, (b) type of barley seed, and (c) shelf position.</p>
In the analysis, do not include any interactions involving shelf position. If you find a significant interaction between watering condition and type of barley seed, carefully interpret the parameter estimates.
<div class="webex-solution">
<button>
Click here to see hints.
</button>
<p>Beware! This example has categorical explanatory variables and so don’t forget to use <em>as.factor</em>. After that you need to carefully form the model in the <em>lm</em> command and interpret the ANOVA table.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><a href="https://richardpmann.com/MATH3823/Solutions/Solutions_2.html">Exercise 2 Solutions can be found here.</a></p>
</div>
</div>


</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>Dobson and Barnett, 3rd edition, Table 2.3.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>Notice that this is a special case of the one-way ANOVA when there are only two-groups.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>Aykroyd, P.J. (1956). Unpublished.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>Source unknown.<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p>Source unknown.<a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script>

/* update total correct if #webex-total_correct exists */
update_total_correct = function() {
  console.log("webex: update total_correct");

  var t = document.getElementsByClassName("webex-total_correct");
  for (var i = 0; i < t.length; i++) {
    p = t[i].parentElement;
    var correct = p.getElementsByClassName("webex-correct").length;
    var solvemes = p.getElementsByClassName("webex-solveme").length;
    var radiogroups = p.getElementsByClassName("webex-radiogroup").length;
    var selects = p.getElementsByClassName("webex-select").length;

    t[i].innerHTML = correct + " of " + (solvemes + radiogroups + selects) + " correct";
  }
}

/* webex-solution button toggling function */
b_func = function() {
  console.log("webex: toggle hide");

  var cl = this.parentElement.classList;
  if (cl.contains('open')) {
    cl.remove("open");
  } else {
    cl.add("open");
  }
}

/* check answers */
check_func = function() {
  console.log("webex: check answers");

  var cl = this.parentElement.classList;
  if (cl.contains('unchecked')) {
    cl.remove("unchecked");
    this.innerHTML = "Hide Answers";
  } else {
    cl.add("unchecked");
    this.innerHTML = "Show Answers";
  }
}

/* function for checking solveme answers */
solveme_func = function(e) {
  console.log("webex: check solveme");

  var real_answers = JSON.parse(this.dataset.answer);
  var my_answer = this.value;
  var cl = this.classList;
  if (cl.contains("ignorecase")) {
    my_answer = my_answer.toLowerCase();
  }
  if (cl.contains("nospaces")) {
    my_answer = my_answer.replace(/ /g, "")
  }

  if (my_answer == "") {
    cl.remove("webex-correct");
    cl.remove("webex-incorrect");
  } else if (real_answers.includes(my_answer)) {
    cl.add("webex-correct");
    cl.remove("webex-incorrect");
  } else {
    cl.add("webex-incorrect");
    cl.remove("webex-correct");
  }

  // match numeric answers within a specified tolerance
  if(this.dataset.tol > 0){
    var tol = JSON.parse(this.dataset.tol);
    var matches = real_answers.map(x => Math.abs(x - my_answer) < tol)
    if (matches.reduce((a, b) => a + b, 0) > 0) {
      cl.add("webex-correct");
    } else {
      cl.remove("webex-correct");
    }
  }

  // added regex bit
  if (cl.contains("regex")){
    answer_regex = RegExp(real_answers.join("|"))
    if (answer_regex.test(my_answer)) {
      cl.add("webex-correct");
    }
  }

  update_total_correct();
}

/* function for checking select answers */
select_func = function(e) {
  console.log("webex: check select");

  var cl = this.classList

  /* add style */
  cl.remove("webex-incorrect");
  cl.remove("webex-correct");
  if (this.value == "answer") {
    cl.add("webex-correct");
  } else if (this.value != "blank") {
    cl.add("webex-incorrect");
  }

  update_total_correct();
}

/* function for checking radiogroups answers */
radiogroups_func = function(e) {
  console.log("webex: check radiogroups");

  var checked_button = document.querySelector('input[name=' + this.id + ']:checked');
  var cl = checked_button.parentElement.classList;
  var labels = checked_button.parentElement.parentElement.children;

  /* get rid of styles */
  for (i = 0; i < labels.length; i++) {
    labels[i].classList.remove("webex-incorrect");
    labels[i].classList.remove("webex-correct");
  }

  /* add style */
  if (checked_button.value == "answer") {
    cl.add("webex-correct");
  } else {
    cl.add("webex-incorrect");
  }

  update_total_correct();
}

window.onload = function() {
  console.log("webex onload");
  /* set up solution buttons */
  var buttons = document.getElementsByTagName("button");

  for (var i = 0; i < buttons.length; i++) {
    if (buttons[i].parentElement.classList.contains('webex-solution')) {
      buttons[i].onclick = b_func;
    }
  }

  var check_sections = document.getElementsByClassName("webex-check");
  console.log("check:", check_sections.length);
  for (var i = 0; i < check_sections.length; i++) {
    check_sections[i].classList.add("unchecked");

    let btn = document.createElement("button");
    btn.innerHTML = "Show Answers";
    btn.classList.add("webex-check-button");
    btn.onclick = check_func;
    check_sections[i].appendChild(btn);

    let spn = document.createElement("span");
    spn.classList.add("webex-total_correct");
    check_sections[i].appendChild(spn);
  }

  /* set up webex-solveme inputs */
  var solveme = document.getElementsByClassName("webex-solveme");

  for (var i = 0; i < solveme.length; i++) {
    /* make sure input boxes don't auto-anything */
    solveme[i].setAttribute("autocomplete","off");
    solveme[i].setAttribute("autocorrect", "off");
    solveme[i].setAttribute("autocapitalize", "off");
    solveme[i].setAttribute("spellcheck", "false");
    solveme[i].value = "";

    /* adjust answer for ignorecase or nospaces */
    var cl = solveme[i].classList;
    var real_answer = solveme[i].dataset.answer;
    if (cl.contains("ignorecase")) {
      real_answer = real_answer.toLowerCase();
    }
    if (cl.contains("nospaces")) {
      real_answer = real_answer.replace(/ /g, "");
    }
    solveme[i].dataset.answer = real_answer;

    /* attach checking function */
    solveme[i].onkeyup = solveme_func;
    solveme[i].onchange = solveme_func;

    solveme[i].insertAdjacentHTML("afterend", " <span class='webex-icon'></span>")
  }

  /* set up radiogroups */
  var radiogroups = document.getElementsByClassName("webex-radiogroup");
  for (var i = 0; i < radiogroups.length; i++) {
    radiogroups[i].onchange = radiogroups_func;
  }

  /* set up selects */
  var selects = document.getElementsByClassName("webex-select");
  for (var i = 0; i < selects.length; i++) {
    selects[i].onchange = select_func;
    selects[i].insertAdjacentHTML("afterend", " <span class='webex-icon'></span>")
  }

  update_total_correct();
}

</script>
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./1_intro.html" class="pagination-link" aria-label="Introduction">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./3_GLM-Theory.html" class="pagination-link" aria-label="GLM Theory">
        <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">GLM Theory</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>