<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>MATH3823 Generalised Linear Models - 5&nbsp; Modelling Proportions</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./6_loglinearmodel.html" rel="next">
<link href="./4_GLM-Fitting.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="webex.css">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./5_logisticmodel.html"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Modelling Proportions</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">MATH3823 Generalised Linear Models</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Weekly schedule</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0_preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Overview</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./1_intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./2_linearmodels.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Essentials of Normal Linear Models</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./3_GLM-Theory.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">GLM Theory</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./4_GLM-Fitting.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">GLM Estimation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./5_logisticmodel.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Modelling Proportions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./6_loglinearmodel.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Loglinear Models</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./7_extendedloglinearmodel.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Extensions to Loglinear models</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="header-section-number">5.1</span> Introduction</a></li>
  <li><a href="#sec-linearlogistic" id="toc-sec-linearlogistic" class="nav-link" data-scroll-target="#sec-linearlogistic"><span class="header-section-number">5.2</span> The logistic model</a></li>
  <li><a href="#focus-on-model-choice-quiz" id="toc-focus-on-model-choice-quiz" class="nav-link" data-scroll-target="#focus-on-model-choice-quiz">Focus on model choice quiz</a></li>
  <li><a href="#sec-overdispersion" id="toc-sec-overdispersion" class="nav-link" data-scroll-target="#sec-overdispersion"><span class="header-section-number">5.3</span> Overdispersion</a></li>
  <li><a href="#odds-ratios-for-2x2-tables" id="toc-odds-ratios-for-2x2-tables" class="nav-link" data-scroll-target="#odds-ratios-for-2x2-tables"><span class="header-section-number">5.4</span> Odds ratios for 2x2 tables</a></li>
  <li><a href="#application-to-doseresponse-experiments" id="toc-application-to-doseresponse-experiments" class="nav-link" data-scroll-target="#application-to-doseresponse-experiments"><span class="header-section-number">5.5</span> Application to dose–response experiments</a></li>
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises"><span class="header-section-number">5.6</span> Exercises</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="sec-proportions" class="quarto-section-identifier"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Modelling Proportions</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="introduction" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="introduction"><span class="header-section-number">5.1</span> Introduction</h2>
<p>In this chapter we will focus on applications of generalised linear modelling where the response variable follows a binomial distribution. This can arise when the outcome is binary, that is it can take one of only two possible values, or is the sum of a set of such binary outcomes. These two outcomes record whether some event of interest has occurred or not. In the simplest case, the response variable, <span class="math inline">\(B\)</span> say, is defined as <span id="eq-bernoullisum"><span class="math display">\[
B =
\begin{cases}
1 &amp; \text{if the event has occurred} \\
0 &amp; \text{if the event has not occurred}
\end{cases}
\tag{5.1}\]</span></span> and we set <span class="math inline">\(Pr(B=1)=p\)</span>, and hence <span class="math inline">\(Pr(B=0)=1-p\)</span>. This is, of course, the definition of a Bernoulli trial leading to a Bernoulli random variables, <span class="math inline">\(B\sim \text{Bernoulli}(p)\)</span>.</p>
<p>Suppose now that there are <span class="math inline">\(m\)</span> similar binary outcomes, <span class="math inline">\(B_i, i=1,\dots,m\)</span> with <span class="math inline">\(Pr(B_i=1)=p\)</span>, and that the total number of times that the event occurred is recorded as the response <span class="math inline">\(Y\)</span>. Assuming that <span class="math inline">\(m\)</span> is known before the trials start, that <span class="math inline">\(p\)</span> is fixed and that the individual Bernoulli trials are independent then <span class="math inline">\(Y\)</span> follows a binomial distribution, <span class="math inline">\(Y\sim \text{B}(m, p)\)</span> with probability mass function <span id="eq-binomial"><span class="math display">\[
f(y) = {m \choose y} p^y(1-p)^{m-y}.
\tag{5.2}\]</span></span> Note that the binomial random variable can be thought of as the sum of i.i.d Bernoulli random variables, <span class="math inline">\(Y= B_1+\cdots + B_m\)</span>, if that is helpful.</p>
<p>The Binomial distribution <span class="math inline">\(\text{B}(m, p)\)</span> is often described in terms of <em>success</em> and <em>failure</em> and a binomial distribution in terms of the number of successes in <span class="math inline">\(m\)</span> independent trials, where <span class="math inline">\(p\)</span> is the probability of success in each trial. The term <em>success</em> need not correspond to a favourable outcome; it is merely the language traditionally used in connection with this model. For example, success might correspond to death.</p>
<p>Of course, the special case with <span class="math inline">\(m=1\)</span> reduces to the Bernoulli distribution. Further, if <span class="math inline">\(Y_1 \sim \text{B}(m_1,p)\)</span> and independently <span class="math inline">\(Y_2 \sim \text{B}(m_2,p)\)</span>, then <span class="math inline">\(Y_1+Y_2\)</span> also follows a binomial distribution, <span class="math inline">\(\text{B}(m_1+m_2,p)\)</span> – note that is only valid when <span class="math inline">\(p\)</span> is common.</p>
<p>Recall that the binomial can be re-written in the exponential family form of <a href="3_GLM-Theory.html#eq-exponential-family">Equation&nbsp;<span>3.3</span></a> with <span class="math display">\[
f(y)  = \exp \left\{ y\ \mbox{logit } p  + m \log (1-p) + \log {m \choose y}\right\},
\]</span> with natural or canonical parameter <span class="math inline">\(\theta=\text{logit} \ p = \log \left( p(1-p)\right),\)</span> scale parameter <span class="math inline">\(\phi=1\)</span>, <span class="math inline">\(b(\theta)=m\log(1+e^\theta)\)</span> and <span class="math inline">\(c(y,\phi)=\log{m\choose y}\)</span> as in <a href="3_GLM-Theory.html#tbl-glm-binomial">Table&nbsp;<span>3.3</span></a>.</p>
</section>
<section id="sec-linearlogistic" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="sec-linearlogistic"><span class="header-section-number">5.2</span> The logistic model</h2>
<p>Throughout this module we have assumed that a response variable, <span class="math inline">\(Y\)</span>, depends on a set of explanatory variables, <span class="math inline">\(\mathbf{x} = \{x_1,\dots, x_p\}\)</span>. In particular, for binomial counts from <span class="math inline">\(\text{B}(m,p)\)</span>, <span class="math inline">\(0&lt;p&lt;1\)</span> with mean <span class="math inline">\(\mu=mp\)</span> we set the link function, <span class="math inline">\(g(\mu)\)</span>, equal to the linear predictor <span class="math inline">\(\eta = \sum \beta_j x_j\)</span> and hence have <span class="math display">\[
g(\mu) = \sum_{j=1}^p \beta_j x_j = \mathbf{x}^T \boldsymbol{\beta}
\]</span> where <span class="math inline">\(\boldsymbol{\beta} = \{\beta_1,\dots,\beta_p\}\)</span> are the linear predictor parameters. Recall that the canonical logit link <a href="3_GLM-Theory.html#eq-g2">Equation&nbsp;<span>3.14</span></a> for the binomial leads to the systematic part of the model <span id="eq-binlogit"><span class="math display">\[
\text{logit}(p) = \log \left( \frac{p}{1-p}\right) = \mathbf{x}^T \boldsymbol{\beta}
\tag{5.3}\]</span></span> but that other links function are possible, such as the probit, <a href="3_GLM-Theory.html#eq-probitlink">Equation&nbsp;<span>3.15</span></a>, the complementary log-log, <a href="3_GLM-Theory.html#eq-clogloglink">Equation&nbsp;<span>3.16</span></a>, and the cauchit <a href="3_GLM-Theory.html#eq-cauchitlink">Equation&nbsp;<span>3.17</span></a>.</p>
<p>This model can alternatively be written <span id="eq-binomialmodel"><span class="math display">\[
Y\ \sim \text{B}(m,p), \quad \text{where }
p=\frac{\exp \{\mathbf{x}^T \boldsymbol{\beta}\}}{1+\exp\{ \mathbf{x}^T \boldsymbol{\beta}\}}
\tag{5.4}\]</span></span> which makes the dependence of <span class="math inline">\(Y\)</span> on <span class="math inline">\(\mathbf{x}\)</span>, and <span class="math inline">\(\boldsymbol{\beta}\)</span>, more explicit.</p>
<p>In general, we might want to consider <span class="math inline">\(n\)</span> independent binomial random variables representing subgroups of the sample with <span class="math inline">\(Y_1\sim \text{B}(m_1,p_1), \dots Y_n\sim \text{B}(m_n,p_n)\)</span>, see <a href="#tbl-linearlogistic">Table&nbsp;<span>5.1</span></a> and hence <span class="math display">\[
\mathbf{Y}\ \sim \text{B}(\mathbf{m},\mathbf{p}), \quad \text{and }
\mathbf{p}=\frac{\exp \{X \boldsymbol{\beta}\}}{1+\exp\{ X \boldsymbol{\beta}\}},
\]</span> with response <span class="math inline">\(\mathbf{Y}=\{Y_1,\dots, Y_n\}\)</span>, <span class="math inline">\(\mathbf{m}=\{m_1,\dots, m_n\}\)</span>, <span class="math inline">\(\mathbf{p}=\{p_1,\dots, p_n\}\)</span>, <span class="math inline">\(X\)</span> being the <span class="math inline">\(n \times p\)</span> design matrix and <span class="math inline">\(\boldsymbol{\beta} = \{\beta_1,\dots,\beta_p\}\)</span> the linear predictor parameters.</p>
<div id="tbl-linearlogistic" class="anchored">
<table class="table">
<caption>Table&nbsp;5.1: Linear logistic model</caption>
<thead>
<tr class="header">
<th></th>
<th style="text-align: center;">Group 1</th>
<th style="text-align: center;">Group 2</th>
<th style="text-align: center;"><span class="math inline">\(\dots\)</span></th>
<th style="text-align: center;">Group <span class="math inline">\(n\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Successes</td>
<td style="text-align: center;"><span class="math inline">\(Y_1\)</span></td>
<td style="text-align: center;"><span class="math inline">\(Y_2\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\dots\)</span></td>
<td style="text-align: center;"><span class="math inline">\(Y_n\)</span></td>
</tr>
<tr class="even">
<td>Failures</td>
<td style="text-align: center;"><span class="math inline">\(m_1-Y_1\)</span></td>
<td style="text-align: center;"><span class="math inline">\(m_2-Y_2\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\dots\)</span></td>
<td style="text-align: center;"><span class="math inline">\(m_n-Y_n\)</span></td>
</tr>
<tr class="odd">
<td><strong>Total</strong></td>
<td style="text-align: center;"><span class="math inline">\(m_1\)</span></td>
<td style="text-align: center;"><span class="math inline">\(m_2\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\dots\)</span></td>
<td style="text-align: center;"><span class="math inline">\(m_n\)</span></td>
</tr>
</tbody>
</table>
</div>
<p>Then we can write down the log likelihood of <span class="math inline">\(\boldsymbol{\beta}\)</span> using <a href="4_GLM-Fitting.html#eq-loglikelihoodgeneral">Equation&nbsp;<span>4.12</span></a> and <a href="#eq-binomial">Equation&nbsp;<span>5.2</span></a> as <span id="eq-binloglikelihood"><span class="math display">\[
l(\boldsymbol{\beta}; \mathbf{y})
=
\sum_{i=1}^n
\left\{
y_i \, \log (p_i) + (m_i-y_i) \log (1-p_i) + \log {m_i \choose y_i}
\right\}
\tag{5.5}\]</span></span> where <span class="math display">\[
p_i=\frac{\exp \{\mathbf{x}_i^T \boldsymbol{\beta}\}}{1+\exp\{ \mathbf{x}_i^T \boldsymbol{\beta}\}}.
\]</span> We would then use the principle of maximum likelihood to estimate <span class="math inline">\(\boldsymbol{\beta}\)</span> <span class="math display">\[
\hat{\boldsymbol{\beta}} = \text{arg} \max_{\boldsymbol{\beta}} \,
l(\boldsymbol{\beta}; \mathbf{y}).
\]</span> Then, the fitted probability are given by <span class="math display">\[
\hat{p}_i=\frac{\exp \{\mathbf{x}_i^T \hat{\boldsymbol{\beta}}\}}{1+\exp\{ \mathbf{x}_i^T \hat{\boldsymbol{\beta}}\}}
\]</span> and corresponding fitted values <span class="math display">\[
\hat y_i = m_i \, \hat{p}_i.
\]</span></p>
<p>The Pearson residuals for binomial data take the form<br>
<span class="math display">\[
e^P_i  =
\frac{y_i - m_i\hat{p}_i}{\sqrt{m_i \hat{p}_i (1 - \hat{p}_i)}} .
\]</span> From the general result <span class="math inline">\(\text{Var}(Y_i)=\phi b''(\theta)\)</span> in <a href="3_GLM-Theory.html#prp-moments">Proposition&nbsp;<span>3.1</span></a>, it can be shown that <span class="math inline">\(\text{Var}(Y_i)=m_i {p}_i (1 - {p}_i)\)</span>. Then, using the estimate of <span class="math inline">\(p_i\)</span> leads to the denominator above.</p>
<p>For large <span class="math inline">\(m_i\)</span>, the usual Normal approximation to the Binomial means that the Pearson residuals are approximately <span class="math inline">\(N(0, 1)\)</span> distributed.</p>
<p>It can be shown that the deviance for the fitted model is <span id="eq-bindev"><span class="math display">\[
D =
2 \sum_{i=1}^n \left\{ y_i \log \left( \frac{y_i} {m_i \hat{p}_i} \right) +
(m_i - y_i) \log \left( \frac{m_i - y_i}{m_i (1 - \hat{p}_i)} \right)
\right\},
\tag{5.6}\]</span></span> which is approximately <span class="math inline">\(\chi^2_{n-r}\)</span> distributed if the model is correct, where <span class="math inline">\(r\)</span> is the number of degrees of freedom in the model (that is the number of parameters or columns of the design matrix).</p>
<p>This formula can be shown to be equivalent to <span class="math display">\[
D = 2 \sum_{j=1}^2 \sum_{i=1}^n O_{ji} \log
\frac{O_{ji}}{E_{ji}}
\]</span> where <span class="math inline">\(O_{ji}\)</span> denotes the observed value and <span class="math inline">\(E_{ji}\)</span> denotes the expected value in cell <span class="math inline">\((j,i)\)</span> of the <span class="math inline">\(2 \times n\)</span> table of successes and failures:</p>
<table class="table">
<caption>Observed and expected frequencies in the linear logistic model</caption>
<thead>
<tr class="header">
<th></th>
<th style="text-align: center;">Group 1</th>
<th style="text-align: center;">Group 2</th>
<th style="text-align: center;"><span class="math inline">\(\dots\)</span></th>
<th style="text-align: center;">Group <span class="math inline">\(n\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Successes, <span class="math inline">\(j=1\)</span></td>
<td style="text-align: center;"><span class="math inline">\(O_{11}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(O_{12}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\dots\)</span></td>
<td style="text-align: center;"><span class="math inline">\(O_{1n}\)</span></td>
</tr>
<tr class="even">
<td></td>
<td style="text-align: center;"><span class="math inline">\(E_{11}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(E_{12}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\dots\)</span></td>
<td style="text-align: center;"><span class="math inline">\(E_{1n}\)</span></td>
</tr>
<tr class="odd">
<td>Failures, <span class="math inline">\(j=2\)</span></td>
<td style="text-align: center;"><span class="math inline">\(O_{21}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(O_{22}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\dots\)</span></td>
<td style="text-align: center;"><span class="math inline">\(O_{2n}\)</span></td>
</tr>
<tr class="even">
<td></td>
<td style="text-align: center;"><span class="math inline">\(E_{21}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(E_{22}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\dots\)</span></td>
<td style="text-align: center;"><span class="math inline">\(E_{2n}\)</span></td>
</tr>
</tbody>
</table>
<p>Another goodness-of-fit statistic is the Pearson chi-squared statistic: <span class="math display">\[
X^2 = \sum_{j=1}^2 \sum_{i=1}^n \frac{(O_{ji} - E_{ji})^2}{E_{ji}}.
\]</span> This is asymptotically equivalent to the deviance <a href="#eq-bindev">Equation&nbsp;<span>5.6</span></a> (proof is by Taylor series expansion; omitted). Thus, asymptotically, <span class="math inline">\(X^2\)</span> is also approximately <span class="math inline">\(\chi^2_{n-r}\)</span> distributed. Both approximations can be poor if the expected frequencies are small, but <span class="math inline">\(X^2\)</span> copes slightly better with this problem. See Dobson, p.136 for more details.</p>
</section>
<section id="focus-on-model-choice-quiz" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="focus-on-model-choice-quiz">Focus on model choice quiz</h2>
<p>Test knowledge recall and comprehension to reinforce ideas of linear and non-linear models. More questions to be added later.</p>
<div class="webex-box">
<div class="webex-check">
<ol type="1">
<li>Which of the following is NOT a true statements about modelling?
<div id="radio_FBWHFBNHHH" class="webex-radiogroup">
<label><input type="radio" autocomplete="off" name="radio_FBWHFBNHHH" value="answer"> <span>The context of the problem and description of the data can be ignored – it's only the data that matter</span></label><label><input type="radio" autocomplete="off" name="radio_FBWHFBNHHH" value=""> <span>Goodness of fit can be assessed using the model residuals.</span></label><label><input type="radio" autocomplete="off" name="radio_FBWHFBNHHH" value=""> <span>Some situations might suggest more than one model to try.</span></label><label><input type="radio" autocomplete="off" name="radio_FBWHFBNHHH" value=""> <span>All model assumptions should be checked.</span></label><label><input type="radio" autocomplete="off" name="radio_FBWHFBNHHH" value=""> <span>It is important to plot the fitted model on the same graph as the data.</span></label>
</div></li>
<li>Which of the following is a true statements about linear regression?
<div id="radio_UIJPPYTVZB" class="webex-radiogroup">
<label><input type="radio" autocomplete="off" name="radio_UIJPPYTVZB" value=""> <span>It is always possible to use the fitted model for extrapolation.</span></label><label><input type="radio" autocomplete="off" name="radio_UIJPPYTVZB" value="answer"> <span>It is always important to check model residuals.</span></label><label><input type="radio" autocomplete="off" name="radio_UIJPPYTVZB" value=""> <span>When there is a moderate correlation then the relationship between variables is always linear.</span></label><label><input type="radio" autocomplete="off" name="radio_UIJPPYTVZB" value=""> <span>A linear model will fit best when the correlation is close to zero.</span></label><label><input type="radio" autocomplete="off" name="radio_UIJPPYTVZB" value=""> <span>A linear model should always be the first model considered.</span></label>
</div></li>
<li>Which of the following is a true statements about logistic regression?
<div id="radio_YAXKBPDFQB" class="webex-radiogroup">
<label><input type="radio" autocomplete="off" name="radio_YAXKBPDFQB" value=""> <span>Should only be used if a linear model is not a good fit to the data.</span></label><label><input type="radio" autocomplete="off" name="radio_YAXKBPDFQB" value=""> <span>The explanatory variables follow a binomial distribution</span></label><label><input type="radio" autocomplete="off" name="radio_YAXKBPDFQB" value=""> <span>A logisitc model should always be used if the correlation is close to zero.</span></label><label><input type="radio" autocomplete="off" name="radio_YAXKBPDFQB" value=""> <span>It is always possible to use the fitted model for extrapolation.</span></label><label><input type="radio" autocomplete="off" name="radio_YAXKBPDFQB" value="answer"> <span>The response variable follows a binomial distribution.</span></label>
</div></li>
</ol>
</div>
<div class="webex-solution">
<button>
Click here to see explanations
</button>
<p>More detail will be added later.</p>
<ol type="1">
<li><p>The starting point should always to learn about the background to a data set as this often suggests models to consider, appropriate distributions and any potential problems. Hence saying that it is only the data that maters is inappropriate.</p></li>
<li><p>Of course there are many important things to check, but looking at residuals is one of the most important.</p></li>
<li><p>Logistic regression assumes that the data follow a binomial distribution.</p></li>
</ol>
</div>
</div>
<!--
The graphs below are for use in the following questions.

::: {.cell}
::: {.cell-output-display}
![](5_logisticmodel_files/figure-html/unnamed-chunk-4-1.png){width=672}
:::
:::

-->
</section>
<section id="sec-overdispersion" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="sec-overdispersion"><span class="header-section-number">5.3</span> Overdispersion</h2>
<p>Examination of residuals and deviances may indicate that a model is not an adequate fit to the data. One possible reason is <em>overdispersion</em>. In particular, it is advisable to compare the residual deviance of the proposed model with the corresponding degrees of freedom. If the ratio, deviance divided by degrees of freedom, is substantially greater than 1, then there is evidence for overdispersion – substantially less than 1 indicates under dispersion but that is very rare. Overdispersion can occur for any error distribution where the variance is linked to the mean — e.g.&nbsp;Binomial, Poisson. In the binomial case, overdispersion is called <em>extra-Binomial</em> variation.</p>
<p>Recall that if <span class="math inline">\(Y_i \sim \text{Bin}(m_i, p_i)\)</span>, <span class="math inline">\(\text{Var}(Y_i) = m_i p_i (1 - p_i)\)</span>. Overdispersion occurs if observations which have been modelled by a <span class="math inline">\(\text{Bin}(m_i, \hat{p}_i)\)</span> distribution have substantially greater variation than <span class="math inline">\(m_i \hat{p}_i (1 - \hat{p}_i)\)</span>. This will lead to a value of <span class="math inline">\(D\)</span> substantially greater than the expected value of <span class="math inline">\(n - r\)</span>. This can occur if the model is missing appropriate explanatory variables or has the wrong link function, or if the <span class="math inline">\(Y_i\)</span> are not independent.</p>
<p>One solution is to include an extra parameter <span class="math inline">\(\tau\)</span> in the model so that <span class="math inline">\(\text{Var}(Y_i) = \tau \times m_i p_i (1 - p_i)\)</span>. For more details, see Section 7.7 of Dobson or Chapter 6 of Collett (1991) <em>Modelling Binary data</em>, Chapman &amp; Hall.</p>
<p>The <span class="math inline">\(\texttt{glm}\)</span> function in <strong>R</strong> allows for <em>extra-Binomial</em> variation by setting <span class="math inline">\(\texttt{family=quasibinomial()}\)</span> with the usual link functions available.</p>
</section>
<section id="odds-ratios-for-2x2-tables" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="odds-ratios-for-2x2-tables"><span class="header-section-number">5.4</span> Odds ratios for 2x2 tables</h2>
<p>In the special case of the data forming a <span class="math inline">\(2 \times 2\)</span> table, then a commonly calculated summary statistic is the <em>odds ratio</em>. This is a measure of association between the presence or absence of some property and an outcome. It represents the odds that an outcome will occur given presence, compared to the odds of the outcome occurring in the absence of that property.</p>
<p>The following <span class="math inline">\(2 \times 2\)</span> table summarizes the different possibilities.</p>
<table class="table">
<thead>
<tr class="header">
<th></th>
<th>Success</th>
<th>Failure</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Present</td>
<td><span class="math inline">\(y_1\)</span></td>
<td><span class="math inline">\(m_1-y_1\)</span></td>
</tr>
<tr class="even">
<td>Absent</td>
<td><span class="math inline">\(y_2\)</span></td>
<td><span class="math inline">\(m_2-y_2\)</span></td>
</tr>
</tbody>
</table>
<p>Similarly, by dividing by the corresponding row total, the probabilities are summaries as follows.</p>
<table class="table">
<thead>
<tr class="header">
<th></th>
<th>Success</th>
<th>Failure</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Present</td>
<td><span class="math inline">\(\pi_1\)</span></td>
<td><span class="math inline">\(1-\pi_1\)</span></td>
</tr>
<tr class="even">
<td>Absent</td>
<td><span class="math inline">\(\pi_2\)</span></td>
<td><span class="math inline">\(1-\pi_2\)</span></td>
</tr>
</tbody>
</table>
<p>There are conditional probabilities, for example <span class="math inline">\(\text{Pr}(\text{Success} | \text{Present})\)</span> etc., and form a <em>stochastic matrix</em> where sum of each row is now 1.</p>
<p>For each row, the <em>odds</em> of success is defined by <span class="math display">\[
O_i = \pi_i/(1-\pi_i), \quad i=1,2,
\]</span> and a comparison between these two probabilities is given by the <em>odds ratio</em> <span class="math display">\[
\phi = \frac{O_1}{O_2} = \frac{\pi_1(1-\pi_2)}{\pi_2(1-\pi_1)}.
\]</span> If <span class="math inline">\(\phi=1\)</span> then the property does not affect the odds of success, <span class="math inline">\(\phi&gt;1\)</span> indicates that the property is associated with higher odds of success, and <span class="math inline">\(\phi&lt;1\)</span> indicates the property is associated with lower odds of success.</p>
<p>Note that the <em>log-odds</em>, <span class="math inline">\(\log O_i = \log \left(\pi_i/(1-\pi_i) \right)\)</span>, which is the <span class="math inline">\(\text{logit}(\pi_i),\)</span> and hence is the natural parameter in the regular exponential family form of the binomial distribution.</p>
<p>Finally, an approximate 100(1-<span class="math inline">\(\alpha\)</span>)% confidence interval, <span class="math inline">\(\left(\phi_{\alpha/2},\phi_{1-\alpha/2}\right)\)</span>, for the odds ratio is calculated using the formulas: <span class="math display">\[
\phi_{\alpha/2} = \phi \times \exp\left(-z_{1-\alpha/2}\sqrt{\frac{1}{y_1}+\frac{1}{(m_1-y_1)}+\frac{1}{y_2}+\frac{1}{(m_2-y_2)}}\right)
\]</span> and <span class="math display">\[
\phi_{1-\alpha/2} = \phi \times \exp\left(+z_{1-\alpha/2}
\sqrt{\frac{1}{y_1}+\frac{1}{(m_1-y_1)}+\frac{1}{y_2}+\frac{1}{(m_2-y_2)}}\right)
\]</span> where <span class="math inline">\(z_{1-\alpha/2}\)</span> is such that <span class="math inline">\(\text{Pr}(Z \le z_{1-\alpha/2})=1-\alpha/2\)</span>. In particular, for a 95% confidence interval <span class="math inline">\(z_{1-\alpha/2}=z_{0.975}=1.96\)</span>.</p>
<p>If the confidence interval for the odds ratio includes the value 1 then the calculated odds ratio would not be considered statistically significant.</p>
</section>
<section id="application-to-doseresponse-experiments" class="level2" data-number="5.5">
<h2 data-number="5.5" class="anchored" data-anchor-id="application-to-doseresponse-experiments"><span class="header-section-number">5.5</span> Application to dose–response experiments</h2>
<p>A variable dose of some reagent is administered to each study subject, and the occurrence of a specific response is recorded. This is a <em>dose–response</em> experiment, one of the first uses of regression models for Bernoulli (or Binomial) responses.</p>
<p>For example, the <a href="#tbl-beetledata2">Table&nbsp;<span>5.2</span></a> (including the information from <a href="1_intro.html#tbl-beetle-data">Table&nbsp;<span>1.1</span></a>) gives the number of beetles killed <span class="math inline">\(y_i\)</span> and the number not killed <span class="math inline">\((m_i-y_i)\)</span> out of a total number <span class="math inline">\(m_i\)</span> that were exposed to a dose <span class="math inline">\(x_i\)</span> of gaseous carbon disulphide, for <span class="math inline">\(n=8\)</span> dose levels <span class="math inline">\(i=1,\dots,8\)</span> (Dobson: pp.109 in 1st edn; pp.119 in 2nd edn; pp.127 in 3rd edn). The proportion killed <span class="math inline">\(p_i = y_i/m_i\)</span> at each dose level <span class="math inline">\(i\)</span> is also shown in <a href="#tbl-beetledata2">Table&nbsp;<span>5.2</span></a> and plotted in <a href="#fig-beetle2">Figure&nbsp;<span>5.1</span></a>.</p>
<div id="tbl-beetledata2" class="anchored">
<table class="table">
<caption>Table&nbsp;5.2: Numbers of beetles killed by five hours of exposure to 8 different concentrations of gaseous carbon disulphide</caption>
<colgroup>
<col style="width: 18%">
<col style="width: 18%">
<col style="width: 18%">
<col style="width: 18%">
<col style="width: 18%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;"><p>Dose</p>
<p><span class="math inline">\(x_i\)</span></p></th>
<th style="text-align: center;"><p>No.&nbsp;of beetle</p>
<p><span class="math inline">\(m_i\)</span></p></th>
<th style="text-align: center;"><p>No.&nbsp;killed</p>
<p><span class="math inline">\(y_i\)</span></p></th>
<th style="text-align: center;"><p>No.&nbsp;not killed</p>
<p><span class="math inline">\(m_i-y_i\)</span></p></th>
<th style="text-align: center;"><p>Proportion</p>
<p><span class="math inline">\(p_ i=y_i/m_i\)</span></p></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">1.6907</td>
<td style="text-align: center;">59</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">53</td>
<td style="text-align: center;">0.10</td>
</tr>
<tr class="even">
<td style="text-align: center;">1.7242</td>
<td style="text-align: center;">60</td>
<td style="text-align: center;">13</td>
<td style="text-align: center;">47</td>
<td style="text-align: center;">0.22</td>
</tr>
<tr class="odd">
<td style="text-align: center;">1.7552</td>
<td style="text-align: center;">62</td>
<td style="text-align: center;">18</td>
<td style="text-align: center;">44</td>
<td style="text-align: center;">0.29</td>
</tr>
<tr class="even">
<td style="text-align: center;">1.7842</td>
<td style="text-align: center;">56</td>
<td style="text-align: center;">28</td>
<td style="text-align: center;">28</td>
<td style="text-align: center;">0.50</td>
</tr>
<tr class="odd">
<td style="text-align: center;">1.8113</td>
<td style="text-align: center;">63</td>
<td style="text-align: center;">52</td>
<td style="text-align: center;">11</td>
<td style="text-align: center;">0.83</td>
</tr>
<tr class="even">
<td style="text-align: center;">1.8369</td>
<td style="text-align: center;">59</td>
<td style="text-align: center;">53</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">0.90</td>
</tr>
<tr class="odd">
<td style="text-align: center;">1.8610</td>
<td style="text-align: center;">62</td>
<td style="text-align: center;">61</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">0.98</td>
</tr>
<tr class="even">
<td style="text-align: center;">1.8839</td>
<td style="text-align: center;">60</td>
<td style="text-align: center;">60</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">1.00</td>
</tr>
</tbody>
</table>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mar=</span><span class="fu">c</span>(<span class="dv">4</span>, <span class="dv">4</span>, <span class="dv">0</span>, <span class="dv">1</span>))</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>beetle <span class="ot">=</span> <span class="fu">read.table</span>(<span class="st">"https://richardpmann.com/MATH3823/Datasets/beetle.txt"</span>, <span class="at">header=</span>T)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>dose <span class="ot">=</span> beetle<span class="sc">$</span>dose</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>mortality <span class="ot">=</span> beetle<span class="sc">$</span>died<span class="sc">/</span>beetle<span class="sc">$</span>total</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(dose, mortality, <span class="at">pch=</span><span class="dv">16</span>,</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlim=</span><span class="fu">c</span>(<span class="fl">1.65</span>, <span class="fl">1.90</span>), <span class="at">xlab =</span><span class="st">"Dose"</span>,</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylim=</span><span class="fu">c</span>(<span class="sc">-</span><span class="fl">0.1</span>, <span class="fl">1.1</span>),  <span class="at">ylab=</span><span class="st">"Mortality"</span>)</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>), <span class="at">lty=</span><span class="dv">2</span>)</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>y <span class="ot">=</span> <span class="fu">cbind</span>(beetle<span class="sc">$</span>died, beetle<span class="sc">$</span>total<span class="sc">-</span>beetle<span class="sc">$</span>died)</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>glm.fit <span class="ot">=</span> <span class="fu">glm</span>(y <span class="sc">~</span> dose, <span class="at">family=</span><span class="fu">binomial</span>(<span class="at">link=</span><span class="st">'logit'</span>))</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>output.dose <span class="ot">=</span> <span class="fu">seq</span>(<span class="fl">1.6</span>,<span class="fl">1.95</span>,<span class="fl">0.001</span>)</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>fitted <span class="ot">=</span> <span class="fu">predict</span>(glm.fit, <span class="fu">data.frame</span>(<span class="at">dose=</span>output.dose), <span class="at">type=</span><span class="st">"response"</span>)</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(output.dose, fitted)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-beetle2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="5_logisticmodel_files/figure-html/fig-beetle2-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figure&nbsp;5.1: Beetle mortality rates with fitted dose-response curves.</figcaption>
</figure>
</div>
</div>
</div>
<p>Now <a href="#eq-binomialmodel">Equation&nbsp;<span>5.4</span></a> motivates modelling the beetle data as <span class="math display">\[
Y_i \sim \text{B}(m_i,p_i), \quad \mbox{for } i=1,\dots, n=8
\]</span> where <span class="math display">\[
\eta_i = \alpha + \beta x_i
\]</span> and so <span class="math display">\[
p_i=\frac{\exp\{\alpha+\beta x_i\}}{(1+\exp\{\alpha+\beta x_i\})}.
\]</span></p>
<p>To fit this model in <strong>R</strong>, a matrix with columns containing the numbers killed <span class="math inline">\(y_i\)</span> and the numbers not killed <span class="math inline">\(m_i-y_i\)</span> is first calculated</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>y <span class="ot">=</span> <span class="fu">cbind</span>(beetle<span class="sc">$</span>died, beetle<span class="sc">$</span>total<span class="sc">-</span>beetle<span class="sc">$</span>died)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(y)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>     [,1] [,2]
[1,]    6   53
[2,]   13   47
[3,]   18   44
[4,]   28   28
[5,]   52   11
[6,]   53    6</code></pre>
</div>
</div>
<p>which is then used in the <span class="math inline">\(\texttt{glm}\)</span> command</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>glm.fit <span class="ot">=</span> <span class="fu">glm</span>(y <span class="sc">~</span> dose, <span class="at">family=</span>binomial)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>The model parameter estimates are given by</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coefficients</span>(glm.fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)        dose 
  -60.71745    34.27033 </code></pre>
</div>
</div>
<p>and hence</p>
<p><span id="eq-fittedlogisitc"><span class="math display">\[
\hat p_i = \frac{\exp\{-60.7 + 34.3 x_i\}}{(1+\exp\{ -60.7 + 34.3x_i\})}.
\tag{5.7}\]</span></span></p>
<p>Further, the deviance if given by</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">deviance</span>(glm.fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 11.23223</code></pre>
</div>
</div>
<p>or more helpfully a full summary, which contains parameter estimates and deviance values using</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(glm.fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = y ~ dose, family = binomial)

Coefficients:
            Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)  -60.717      5.181  -11.72   &lt;2e-16 ***
dose          34.270      2.912   11.77   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 284.202  on 7  degrees of freedom
Residual deviance:  11.232  on 6  degrees of freedom
AIC: 41.43

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
<p>or the anova table</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(glm.fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Deviance Table

Model: binomial, link: logit

Response: y

Terms added sequentially (first to last)

     Df Deviance Resid. Df Resid. Dev
NULL                     7    284.202
dose  1   272.97         6     11.232</code></pre>
</div>
</div>
<p>Clearly, many of the results are repeated in the various <strong>R</strong> output.</p>
<p>When considering testing model goodness of fit, it is important to distinguish between deviance values which compare a given model with the saturated model and deviance values which compare two competing models. For example, in the Analysis of Deviance Table, the right hand values compare the Null model with the saturated and the model including dose with the saturated. Whereas the left hand value is relevant to the comparison of Null model with the mode including dose.</p>
<p><strong>Summary of results:</strong><br>
From the output, we can first test if the Null model, which contains only a constant term, is a good fit to the data using the hypotheses: <span class="math display">\[
H_0: \mbox{Null model is true} \mbox{ against } H_1: \mbox{Null model is false}.
\]</span> From the output, note that the Null deviance is <span class="math inline">\(D_0=284.202\)</span> and that this model has <span class="math inline">\(r_0=1\)</span> parameters. Therefore, <span class="math inline">\(D_0\)</span> follows a <span class="math inline">\(\chi^2\)</span> distribution with <span class="math inline">\(n-r_0=8-1=7\)</span> degrees of freedom and hence the p-value is:</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pchisq</span>(<span class="fl">284.202</span>, <span class="dv">7</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.425247e-57</code></pre>
</div>
</div>
<p>This means that we reject <span class="math inline">\(H_0\)</span> as the observed value of <span class="math inline">\(D\)</span> is in the upper tail of the <span class="math inline">\(\chi^2\)</span> distribution.</p>
<p>If we had obtained a non-significant result, then we would stop the analysis and conclude that the Null model is an adequate fit.</p>
<p>Next, consider testing the model which includes the explanatory variable where the the hypotheses are <span class="math display">\[
H_0: \mbox{Null model is true} \mbox{ against } H_1: \mbox{Model with dose is true}.
\]</span> From the output, the deviance of the proposed model is <span class="math inline">\(D_1=11.232\)</span> with <span class="math inline">\(r_1=2\)</span> parameters. The test statistics is then <span class="math inline">\(D_0-D_1=284.202-11.232=272.97\)</span> which follows a <span class="math inline">\(\chi^2\)</span> distribution with <span class="math inline">\(r_1-r_0=2-1=1\)</span> degrees of freedom. The p-value is then</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pchisq</span>(<span class="fl">272.97</span>, <span class="dv">1</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.556369e-61</code></pre>
</div>
</div>
<p>and we reject <span class="math inline">\(H_0\)</span> in favour of <span class="math inline">\(H_1\)</span> and conclude that dose is important.</p>
<p>We can finish the testing by checking if this model is a good fit to the data. That is, <span class="math display">\[
H_0: \mbox{The model with dose is true} \mbox{ against } H_1: \mbox{The model with dose is false}
\]</span> The deviance of this is <span class="math inline">\(D_1=11.232\)</span> with <span class="math inline">\(r_1=2\)</span> parameters which follows a <span class="math inline">\(\chi^2\)</span> distribution with <span class="math inline">\(n-r_1=8-2=6\)</span> degrees of freedom and has p=value</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pchisq</span>(<span class="fl">11.232</span>, <span class="dv">6</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.08146544</code></pre>
</div>
</div>
<p>which means that we accept <span class="math inline">\(H_0\)</span> at the 5% level and conclude that this model is an adequate fit to the data.</p>
<p>Finally, we can look at the residuals:</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mar=</span><span class="fu">c</span>(<span class="dv">4</span>, <span class="dv">4</span>, <span class="dv">0</span>, <span class="dv">1</span>))</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>fit.resids <span class="ot">=</span> <span class="fu">residuals</span>(glm.fit, <span class="at">type=</span><span class="st">"deviance"</span>)</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(dose, fit.resids, <span class="at">pch=</span><span class="dv">16</span>)</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="dv">0</span>, <span class="at">lty=</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="5_logisticmodel_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>These show a very slight <em>u-shaped</em> pattern and hence it would be work exploring fitting using the other link functions. For this data set, the complementary log-log (cloglog) link has a slightly better fit, see <a href="3_GLM-Theory.html#fig-beetlelinks">Figure&nbsp;<span>3.4</span></a>, but a slight pattern remains.</p>
<p>Before finishing, suppose that we wish to predict, by hand, the probability for dose level <span class="math inline">\(x_0=1.85\)</span>, say, and the expected number of beetles killed when <span class="math inline">\(m_0=60\)</span> beetles, say, are exposed.</p>
<p>The probability is predicted as <span class="math display">\[
\hat p_i = \frac{\exp\{-60.7 + 34.3 x_0\}}{(1+\exp\{ -60.7 + 34.3x_0\})} = 0.936
\]</span> and the expected number of beetles <span class="math display">\[
m_0 \, \hat p_i =  56.2
\]</span> Finally, suppose that we wish to find the minimum dose which kills 95% of the beetles, that is <span class="math inline">\(p_0=0.95\)</span> which requires us to invert the logistic equation.</p>
<p>In general, suppose we wish to find <span class="math inline">\(x_p\)</span> which corresponds to proportion <span class="math inline">\(p\)</span> then <span class="math display">\[
x_p= \frac{1}{\beta} \left\{ \log\left(\frac{p}{1-p}\right)-\alpha \right\}
\]</span> and hence here <span class="math inline">\(\hat x_p= 1.856\)</span>.</p>
</section>
<section id="exercises" class="level2" data-number="5.6">
<h2 data-number="5.6" class="anchored" data-anchor-id="exercises"><span class="header-section-number">5.6</span> Exercises</h2>
<div class="webex-box">
<p>5.1. Which of the following descriptions suggest that a logistic regression should be considered. Justify your answers.</p>
<ol type="a">
<li><p>A pharmaceutical company perform clinical trials where volunteers are given varying doses of an experimental drug to study the chances of potential negative side effects. From historical data 4 previous volunteers out of a total of 120 have had negative side effects.</p></li>
<li><p>A credit card company monitors sales to identify fraudulent transactions. On the previous five days, 26, 20, 18, 19 and 21 regular transactions occurred before the first fraudulent transaction was identified.</p></li>
<li><p>A national internet service provider monitors the frequency of helpline phone calls regarding internet failures. From records, there are an average of 0.27 calls per day.</p></li>
<li><p>The University Student Education Services monitor the success of registered students every year. In particular, they record whether students pass their examinations, or not, and what <em>application score</em> they were given when they applied for a place at University.</p></li>
</ol>
<div class="webex-solution">
<button>
Click here to see hints.
</button>
<p>For each, consider what is response, is it binomial and what is the explanatory variable. In cases which are not binomial, suggest an alternative distribution.</p>
</div>
<p><br>
</p>
<p>5.2. For each of the situation produce appropriate graphs within RStudio. Describe the type of relationship, if any, shown in the plots. Is a linear, a logistic, or some other model appropriate? If linear or logistic, go ahead with model fitting and perform a residual analysis. Do you think that prediction from the model would be reliable? Justify each step of your analysis.</p>
<ol type="a">
<li><p>A UK loan company requires a detailed questionnaire to be completed for any loan application including such information as income, regular expenditure, previous loan details and other information from data analytics and consumer credit reporting companies. All the information is combined into a single <em>credit score</em> from 0 to 1000. A large sample of credit applicants were contacted by an independent market research company to discover the outcome of their application. The data file <em>loans.csv</em> gives the number of successful application, number declined and the credit scores.</p></li>
<li><p>A small estate agent company is interested in studying the changes in sales of houses due to targeted advertising campaigns and in particular to determine if additional spending is worthwhile. The company record the weekly sales before each advertising campaign and then again for one week a full month later, along with the cost of each campaign. The datafile <em>advertising.csv</em> contains the advertising budget values in pounds and corresponding changes in sale, also in pounds.</p></li>
<li><p>The yield of arable crops is sensitive to the nutrient levels in the soil. A key fertilizer used to boost production is the mineral phosphorus which is applied as phosphorus pentoxide, <span class="math inline">\(P_2O_5\)</span>. At a wheat large farm, various amounts from 0 kg/ha to 80 kg/ha were applied to investigate the effect on wheat yield, in kg/ha. Use the data in file <em>wheat.csv</em> to investigate this situation.</p></li>
<li><p>Cardiac troponin (cTn) is a human protein which is commonly measured in the diagnosis of heart attacks. A small sample of blood is taken from patients suspected of having heart attacks and the level of cardiac troponin is recorded The cardiac troponin levels, in ng/mL, of 100 patients arriving at a hospital Accident &amp; Emergency department with significant chest discomfort along with the later confirmed diagnosis (0=No and 1=Yes).</p></li>
</ol>
<div class="webex-solution">
<button>
Click here to see hints.
</button>
<p>For each, consider what is response, is it binomial and what is the explanatory variable. If the plot reveals a relationship which is either linear or logistic, then follow the appropriate steps previously discussed – check the code blocks in various examples. For the residual analysis, plot a graph of residuals against fitted values and check to a lack of pattern. For the linear cases, also consider the assumption of normality. For example using a histogram.</p>
</div>
<p><br>
</p>
5.3 In the beetle example, use the fitted logistic regression model, <a href="#eq-fittedlogisitc">Equation&nbsp;<span>5.7</span></a>, to predict what dose of gaseous carbon disulphide would kill 90% of beetles. Then, fit alternative link functions to the data and plot the results. Do you think that the choice of link function makes a difference to your conclusions? Justify your answer.
<div class="webex-solution">
<button>
Click here to see hints.
</button>
<p>For the prediction, rearrange the usual expression for <em>p</em> in terms of <em>x</em> and the model parameters to give an expression for <em>x</em>. To fit alternative link functions, just change the argument in the <em>family</em> option.</p>
</div>
<p><br>
</p>
<p>5.4 (Based on Dobson &amp; Barnett, pp 144–145). Suppose there are 2 groups of people: the first group is exposed to some pollutant and the second group is not. In a prospective study, each group is followed for several years and categorised according to the presence or absence of some disease. Let <span class="math inline">\(\pi_i\)</span> denote the probability that a person in group <span class="math inline">\(i\)</span> contracts the disease, <span class="math inline">\(i=1,2.\)</span> The following <span class="math inline">\(2 \times 2\)</span> table summarizes the different possibilities.</p>
<table class="table">
<thead>
<tr class="header">
<th></th>
<th>Diseased</th>
<th>Not diseased</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Exposed</td>
<td><span class="math inline">\(\pi_1\)</span></td>
<td><span class="math inline">\(1-\pi_1\)</span></td>
</tr>
<tr class="even">
<td>Not exposed</td>
<td><span class="math inline">\(\pi_2\)</span></td>
<td><span class="math inline">\(1-\pi_2\)</span></td>
</tr>
</tbody>
</table>
<p>Note that the sum of each row is 1. For each <span class="math inline">\(i=1,2\)</span>, the <em>odds</em> of contracting the disease is defined by <span class="math display">\[
O_i = \pi_i/(1-\pi_i),
\]</span> and a comparison between these two probabilities is given by the <em>odds ratio</em> <span class="math display">\[
\phi = \frac{O_1}{O_2} = \frac{\pi_1(1-\pi_2)}{\pi_2(1-\pi_1)}.
\]</span></p>
<ol type="a">
<li><p>Show that <span class="math inline">\(\phi=1\)</span> if and only if there is no difference between the control and exposed groups. What does it mean if <span class="math inline">\(\phi &gt; 1\)</span>?</p></li>
<li><p>Consider now <span class="math inline">\(m\)</span> tables where each is of this form, with probabilities <span class="math inline">\(\pi_{ij}\)</span> represented by a logistic model <span class="math display">\[
\text{logit}(\pi_{ij}) = \alpha_i + \beta_i x_j, \ i=1,2,\
j=1,\ldots,m,
\]</span> where <span class="math inline">\(x_j\)</span> is some specified quantitative explanatory variable. Interpret the parameters <span class="math inline">\(\alpha_i\)</span> and <span class="math inline">\(\beta_j\)</span>, and give their effect on the log odds ratio <span class="math inline">\(\log \phi_j\)</span>, say, for each table. Show that <span class="math inline">\(\log \phi_j\)</span> is constant across the <span class="math inline">\(m\)</span> tables if <span class="math inline">\(\beta_1 = \beta_2\)</span>.</p></li>
<li><p>Give a practical example where such a model might be appropriate.</p></li>
<li><p>How would you express this model in the R computer language?</p></li>
</ol>
<div class="webex-solution">
<button>
Click here to see hints.
</button>
<p>In (a), one way is easy. For the other way, rearrange the odds ration and consider the ratios of the event occurring and the ratio that the events not occurring. These are only equal if the probabilities are the same. In (b), note that the log odds ratio is exactly the logistic transform. Substitute in and simplify. An example should be easy, and check ealier for the R command.</p>
</div>
<p><br>
</p>
<p>5.5. Consider again the beetle example, but suppose that rather than the actual dose concentration had been measured, instead only whether a <em>Low dose</em> or <em>High dose</em> was used recorded. This would lead to the following table:</p>
<table class="table">
<thead>
<tr class="header">
<th></th>
<th style="text-align: center;">Died</th>
<th style="text-align: center;">Not died</th>
<th style="text-align: center;">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Low dose</td>
<td style="text-align: center;">65</td>
<td style="text-align: center;">172</td>
<td style="text-align: center;">237</td>
</tr>
<tr class="even">
<td>High dose</td>
<td style="text-align: center;">226</td>
<td style="text-align: center;">18</td>
<td style="text-align: center;">244</td>
</tr>
</tbody>
</table>
<p>What are the respective probability of death values in the two dose groups? The <em>relative risk</em> is defined as the ratio of these two values. Calculate the risk of death due to High dose exposure relative to Low dose for this example. How could this value be used to measure the association between dose and death?</p>
<p>What are the respective odds of death in each of the two groups? Calculate the <em>odds ratio</em>, defined as the ratio of these two values. How could this value be used to interpret the data?</p>
<div class="webex-solution">
<button>
Click here to see hints.
</button>
<p>If there is no difference then the relative risk should be 1 and a value substantially different indicates an association. The odds and the odds ratio have a similar interpretation. All measures are do the same thing, but each is standard in particular application areas.</p>
</div>
</div>
<p><br>
</p>
<!-- ::: {.callout-note appearance="default"} -->
<!-- [Exercise 5 Solutions can be found here.](https://richardpmann.com/MATH3823/Solutions_5.html) -->
<!-- ::: -->


</section>

</main> <!-- /main -->
<script>

/* update total correct if #webex-total_correct exists */
update_total_correct = function() {
  console.log("webex: update total_correct");

  var t = document.getElementsByClassName("webex-total_correct");
  for (var i = 0; i < t.length; i++) {
    p = t[i].parentElement;
    var correct = p.getElementsByClassName("webex-correct").length;
    var solvemes = p.getElementsByClassName("webex-solveme").length;
    var radiogroups = p.getElementsByClassName("webex-radiogroup").length;
    var selects = p.getElementsByClassName("webex-select").length;

    t[i].innerHTML = correct + " of " + (solvemes + radiogroups + selects) + " correct";
  }
}

/* webex-solution button toggling function */
b_func = function() {
  console.log("webex: toggle hide");

  var cl = this.parentElement.classList;
  if (cl.contains('open')) {
    cl.remove("open");
  } else {
    cl.add("open");
  }
}

/* check answers */
check_func = function() {
  console.log("webex: check answers");

  var cl = this.parentElement.classList;
  if (cl.contains('unchecked')) {
    cl.remove("unchecked");
    this.innerHTML = "Hide Answers";
  } else {
    cl.add("unchecked");
    this.innerHTML = "Show Answers";
  }
}

/* function for checking solveme answers */
solveme_func = function(e) {
  console.log("webex: check solveme");

  var real_answers = JSON.parse(this.dataset.answer);
  var my_answer = this.value;
  var cl = this.classList;
  if (cl.contains("ignorecase")) {
    my_answer = my_answer.toLowerCase();
  }
  if (cl.contains("nospaces")) {
    my_answer = my_answer.replace(/ /g, "")
  }

  if (my_answer == "") {
    cl.remove("webex-correct");
    cl.remove("webex-incorrect");
  } else if (real_answers.includes(my_answer)) {
    cl.add("webex-correct");
    cl.remove("webex-incorrect");
  } else {
    cl.add("webex-incorrect");
    cl.remove("webex-correct");
  }

  // match numeric answers within a specified tolerance
  if(this.dataset.tol > 0){
    var tol = JSON.parse(this.dataset.tol);
    var matches = real_answers.map(x => Math.abs(x - my_answer) < tol)
    if (matches.reduce((a, b) => a + b, 0) > 0) {
      cl.add("webex-correct");
    } else {
      cl.remove("webex-correct");
    }
  }

  // added regex bit
  if (cl.contains("regex")){
    answer_regex = RegExp(real_answers.join("|"))
    if (answer_regex.test(my_answer)) {
      cl.add("webex-correct");
    }
  }

  update_total_correct();
}

/* function for checking select answers */
select_func = function(e) {
  console.log("webex: check select");

  var cl = this.classList

  /* add style */
  cl.remove("webex-incorrect");
  cl.remove("webex-correct");
  if (this.value == "answer") {
    cl.add("webex-correct");
  } else if (this.value != "blank") {
    cl.add("webex-incorrect");
  }

  update_total_correct();
}

/* function for checking radiogroups answers */
radiogroups_func = function(e) {
  console.log("webex: check radiogroups");

  var checked_button = document.querySelector('input[name=' + this.id + ']:checked');
  var cl = checked_button.parentElement.classList;
  var labels = checked_button.parentElement.parentElement.children;

  /* get rid of styles */
  for (i = 0; i < labels.length; i++) {
    labels[i].classList.remove("webex-incorrect");
    labels[i].classList.remove("webex-correct");
  }

  /* add style */
  if (checked_button.value == "answer") {
    cl.add("webex-correct");
  } else {
    cl.add("webex-incorrect");
  }

  update_total_correct();
}

window.onload = function() {
  console.log("webex onload");
  /* set up solution buttons */
  var buttons = document.getElementsByTagName("button");

  for (var i = 0; i < buttons.length; i++) {
    if (buttons[i].parentElement.classList.contains('webex-solution')) {
      buttons[i].onclick = b_func;
    }
  }

  var check_sections = document.getElementsByClassName("webex-check");
  console.log("check:", check_sections.length);
  for (var i = 0; i < check_sections.length; i++) {
    check_sections[i].classList.add("unchecked");

    let btn = document.createElement("button");
    btn.innerHTML = "Show Answers";
    btn.classList.add("webex-check-button");
    btn.onclick = check_func;
    check_sections[i].appendChild(btn);

    let spn = document.createElement("span");
    spn.classList.add("webex-total_correct");
    check_sections[i].appendChild(spn);
  }

  /* set up webex-solveme inputs */
  var solveme = document.getElementsByClassName("webex-solveme");

  for (var i = 0; i < solveme.length; i++) {
    /* make sure input boxes don't auto-anything */
    solveme[i].setAttribute("autocomplete","off");
    solveme[i].setAttribute("autocorrect", "off");
    solveme[i].setAttribute("autocapitalize", "off");
    solveme[i].setAttribute("spellcheck", "false");
    solveme[i].value = "";

    /* adjust answer for ignorecase or nospaces */
    var cl = solveme[i].classList;
    var real_answer = solveme[i].dataset.answer;
    if (cl.contains("ignorecase")) {
      real_answer = real_answer.toLowerCase();
    }
    if (cl.contains("nospaces")) {
      real_answer = real_answer.replace(/ /g, "");
    }
    solveme[i].dataset.answer = real_answer;

    /* attach checking function */
    solveme[i].onkeyup = solveme_func;
    solveme[i].onchange = solveme_func;

    solveme[i].insertAdjacentHTML("afterend", " <span class='webex-icon'></span>")
  }

  /* set up radiogroups */
  var radiogroups = document.getElementsByClassName("webex-radiogroup");
  for (var i = 0; i < radiogroups.length; i++) {
    radiogroups[i].onchange = radiogroups_func;
  }

  /* set up selects */
  var selects = document.getElementsByClassName("webex-select");
  for (var i = 0; i < selects.length; i++) {
    selects[i].onchange = select_func;
    selects[i].insertAdjacentHTML("afterend", " <span class='webex-icon'></span>")
  }

  update_total_correct();
}

</script>
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./4_GLM-Fitting.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">GLM Estimation</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./6_loglinearmodel.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Loglinear Models</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>