<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>MATH5824 Generalised Linear and Additive Models - 6&nbsp; General Additive Models</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./5_smoothingparameter.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="webex.css">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./6_smoothinginpractice.html"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">General Additive Models</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">MATH5824 Generalised Linear and Additive Models</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Weekly schedule</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0_preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Overview</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./1_introduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Non-parametric Modelling</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./2_basicdefinitions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Introducing Splines</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./3_interpolating.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Interpolating Splines</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./4_smoothing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Smoothing Splines</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./5_smoothingparameter.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Choosing the Smoothing Parameter</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./6_smoothinginpractice.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">General Additive Models</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#overview" id="toc-overview" class="nav-link active" data-scroll-target="#overview"><span class="header-section-number">6.1</span> Overview</a></li>
  <li><a href="#penalised-deviance" id="toc-penalised-deviance" class="nav-link" data-scroll-target="#penalised-deviance"><span class="header-section-number">6.2</span> Penalised deviance</a></li>
  <li><a href="#gams-in-r" id="toc-gams-in-r" class="nav-link" data-scroll-target="#gams-in-r"><span class="header-section-number">6.3</span> GAMs in <strong>R</strong></a></li>
  <li><a href="#coronary-heart-disease-chd-in-south-africa" id="toc-coronary-heart-disease-chd-in-south-africa" class="nav-link" data-scroll-target="#coronary-heart-disease-chd-in-south-africa"><span class="header-section-number">6.4</span> Coronary heart disease (CHD) in South Africa</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">General Additive Models</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="overview" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="overview"><span class="header-section-number">6.1</span> Overview</h2>
<p>So far, we have considered the modelling of a response variable <span class="math inline">\(y\)</span> in terms of a single response variable <span class="math inline">\(x\)</span>. In particular, we have assumed that the form of this relationship is unknown but can be written as <span class="math display">\[
y_i = f(t_i) + \epsilon_i,\qquad \epsilon_i\sim\text{N}(0,\sigma^2)
\]</span> where the <span class="math inline">\(\epsilon_i\)</span> are i.i.d. <span class="math inline">\(\sim\text{N}(0,\sigma^2)\)</span> and <span class="math inline">\(f(t)\)</span> is assumed to be smooth. Given knot positions <span class="math inline">\(\{t_i,\; i=1,\dots,n\}\)</span>, we can estimate <span class="math inline">\(f(t)\)</span> with a smoothing spline <span class="math inline">\(\hat{f}_\lambda(t)\)</span> for given smoothing parameter <span class="math inline">\(\lambda\)</span> and, further, we can estimate <span class="math inline">\(\lambda\)</span> using ordinary or generalised cross validation. This approach is in contrast to simple linear regression where <span class="math inline">\(y\)</span> is expressed as a linear function of the explanatory variable <span class="math inline">\(y_i=\alpha + \beta x_i +\epsilon_i\)</span> which enforces a very inflexible relationship.</p>
<p>In this chapter, we generalise the modelling to describe the dependence of the response variable <span class="math inline">\(y\)</span> on a set of explanatory variables <span class="math inline">\(\mathbf{x}=(x_1,x_2,\dots, x_p)\)</span> where, conditionally on <span class="math inline">\(\mathbf{x}\)</span>, observation <span class="math inline">\(y\)</span> has a distribution which is not necessarily normal.</p>
<p>Just as with a generalised linear model, the <em>general additive model</em> relates a continuous or discrete response variable <span class="math inline">\(Y\)</span> to a set of explanatory variables <span class="math inline">\(\mathbf{x}=(x_1,x_2,\dots, x_p)\)</span> and, again, the model contains three parts:</p>
<p><strong>Random part:</strong> The probability (mass or density) function of <span class="math inline">\(Y\)</span> is assumed to belong to the <em>two-parameter</em> <em>exponential family</em> of distributions with parameters <span class="math inline">\(\theta\)</span> and <span class="math inline">\(\phi\)</span>.</p>
<p><strong>Systematic part:</strong> This is a <em>non-linear predictor equation</em>: <span id="eq-nonlinpred"><span class="math display">\[
\eta = \sum_{j=1}^p f_j(x_j).
\tag{6.1}\]</span></span></p>
<p><strong>Link function:</strong> This is a one-to-one function providing the link between the predictor equation <span class="math inline">\(\eta\)</span> and the mean <span class="math inline">\(\mu = \mbox{E}[Y]\)</span>:</p>
<p><span id="eq-linkfun"><span class="math display">\[
\eta = g(\mu), \quad \mbox{and} \quad \mu  = g^{-1}(\eta) = h(\eta).
\tag{6.2}\]</span></span></p>
<p>Here, <span class="math inline">\(g(\mu)\)</span> is called the <em>link function</em>, and <span class="math inline">\(h(\eta)\)</span> is called the <em>inverse link function</em>.</p>
</section>
<section id="penalised-deviance" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="penalised-deviance"><span class="header-section-number">6.2</span> Penalised deviance</h2>
<p>The spline theory in the previous chapters has assumed Gaussian (normally distributed) data and the identity link function. For non-Gaussian data and/or a non-identity link function, we need to replace the penalised least-squares criterion of <a href="4_smoothing.html#eq-rlambdaf">Equation&nbsp;<span>4.2</span></a> with a <em>penalised deviance</em>: <span id="eq-rlambdafglm1"><span class="math display">\[
R_{\nu}(f, \lambda, \boldsymbol{\beta})
=
D({\mathbf y}, f,\boldsymbol{\beta})  + \lambda \, J_\nu(f),
\tag{6.3}\]</span></span> where <span class="math inline">\(D({\mathbf y}, f,\boldsymbol{\beta})\)</span> is the deviance for the vector <span class="math inline">\(\mathbf{y}\)</span> of observations modeled by a linear predictor that comprises a spline function <span class="math inline">\(f(t)\)</span> of order <span class="math inline">\(\nu\)</span> and possibly also covariate main-effects and interactions. The penalised deviance is then minimised with respect to the spline coefficients <span class="math inline">\(\mathbf{a}\)</span>, <span class="math inline">\(\mathbf{b}\)</span> and regression parameters <span class="math inline">\(\boldsymbol{\beta}\)</span>, if any. Note that the fitted values for <span class="math inline">\(y\)</span> are obtained by applying the inverse link function to the linear predictor <span class="math inline">\(f(t)\)</span>, for example the logistic function when the link is logit.</p>
<p>When there are several smooth terms of order <span class="math inline">\(\nu\)</span> in the model, <span class="math inline">\({\mathbf f} = \{f_1,\dots,f_m\}\)</span>, each may be assigned its own roughness penalty, <span class="math inline">\(\lambda_h\)</span>, and <a href="#eq-rlambdafglm1">Equation&nbsp;<span>6.3</span></a> becomes <span id="eq-Rlambdafglm2"><span class="math display">\[
R_{\nu}(f_1,\dots,f_m, \lambda_1,\dots, \lambda_m, \boldsymbol{\beta}) =
D({\mathbf y}, f_1,\dots,f_m, \boldsymbol{\beta})  + \sum_{h=1}^m \lambda_h J_\nu(f_h)
\tag{6.4}\]</span></span> or we may choose to write this as <span class="math display">\[
R_{\nu}({\mathbf f}, {\boldsymbol \lambda}, \boldsymbol{\beta}) =
D({\mathbf y}, {\mathbf f}, \boldsymbol{\beta})  + \sum_{h=1}^m \lambda_h J_\nu(f_h).
\]</span></p>
</section>
<section id="gams-in-r" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="gams-in-r"><span class="header-section-number">6.3</span> GAMs in <strong>R</strong></h2>
<p>Fitting smoothing splines is straightforward in practice using R. At the beginning of each <strong>R</strong> session, the first step is to load the package <span class="math inline">\(\texttt{mgcv}\)</span> which makes available a set of routines written by Simon Wood of the University of Bath.</p>
<p>The main command is <span class="math inline">\(\texttt{gam}\)</span> which fits a smoothing spline (or, more generally, a general additive model). The <span class="math inline">\(\texttt{gam}\)</span> function is an extension to the <span class="math inline">\(\texttt{glm}\)</span> command for fitting generalised linear models, to allow nonparametric functions of explanatory variables.</p>
<p>The syntax of the <span class="math inline">\(\texttt{gam}\)</span> command is similar to that of <span class="math inline">\(\texttt{glm}\)</span>. Suppose <span class="math inline">\(\texttt{y}\)</span> is a vector of length containing observations of a dependent variable and is another vector of length containing the times of those observations. Then each of the commands</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>out<span class="ot">=</span><span class="fu">gam</span>(y<span class="sc">~</span><span class="fu">s</span>(tt,<span class="at">fx=</span><span class="cn">FALSE</span>,<span class="at">k=</span><span class="dv">6</span>,<span class="at">sp=</span><span class="fl">3.5</span>))</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>out<span class="ot">=</span><span class="fu">gam</span>(y<span class="sc">~</span><span class="fu">s</span>(tt,<span class="at">fx=</span><span class="cn">FALSE</span>,<span class="at">k=</span><span class="dv">6</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>fits a cubic smoothing spline to the dependent variable <span class="math inline">\(\texttt{y}\)</span>. In the first version above, the user explicitly sets the smoothing parameter <span class="math inline">\(\lambda\)</span> (here denoted <span class="math inline">\(\texttt{sp}\)</span>) to the value <span class="math inline">\(3.5\)</span>. In the second version, the optimal value of <span class="math inline">\(\lambda\)</span> is chosen by the routine to minimise the Generalised Cross-Validation criterion, GCV. The notation <span class="math inline">\(\texttt{s(tt)}\)</span> means a smooth function (a cubic smoothing spline in this setting) of the explanatory variable <span class="math inline">\(\texttt{tt}\)</span>. This notation can be viewed as an extension of the model notation used by the <span class="math inline">\(\texttt{glm}\)</span> function. Setting <span class="math inline">\(\texttt{fx=FALSE}\)</span> in function <span class="math inline">\(\texttt{s}\)</span> specifies that the dimensionality of the spline should be free (see later notes). Parameter <span class="math inline">\(\texttt{k}\)</span> of function <span class="math inline">\(\texttt{s}\)</span> specifies the <em>maximum</em> dimensionality of the spline, <strong>and should be set according to the problem and data at hand</strong> since the default value will not be appropriate in general. For example, if <span class="math inline">\(\texttt{tt}\)</span> contains only 6 distinct values, then it would be appropriate to set <span class="math inline">\(\texttt{k=6}\)</span>.</p>
<p>In each of the above examples, output from <span class="math inline">\(\texttt{gam}\)</span> is stored in an object called <span class="math inline">\(\texttt{out}\)</span>. This object contains several components of interest:</p>
<ul>
<li><span class="math inline">\(\texttt{out\$fitted.values}\)</span> is a vector of length <span class="math inline">\(\texttt{n}\)</span> containing the fitted values of the smoothing spline at the data values.</li>
<li><span class="math inline">\(\texttt{out\$gcv.ubre}\)</span> contains the value of the GCV criterion.</li>
<li><span class="math inline">\(\texttt{out\$hat}\)</span> contains the diagonal values of the smoothing matrix, also called the <em>hat</em> matrix. The total degrees of freedom in the model (including the intercept term) is given by <span class="math inline">\(\texttt{sum(out\$hat)}\)</span>.</li>
<li><span class="math inline">\(\texttt{out\$sp}\)</span> contains the smoothing parameter value.</li>
<li><span class="math inline">\(\texttt{summary.gam(out)}\)</span> provides a summary of the smoothed model fit.</li>
<li><span class="math inline">\(\texttt{anova.gam(out)}\)</span> provides an analysis of deviance for the model.</li>
</ul>
<p>Thus, if <span class="math inline">\(\texttt{gam}\)</span> is called without an explicit choice of <span class="math inline">\(\texttt{sp}\)</span> (as in the second example above), the output from <span class="math inline">\(\texttt{gam}\)</span> gives the optimal smoothing parameter value and the corresponding value of the GCV criterion.</p>
<p>To plot a smoothing spline:</p>
<ul>
<li>define a dense set of times spanning the data, at which to plot the smooth curve;</li>
<li>use the <span class="math inline">\(\texttt{predict.gam}\)</span> function to compute the cubic spline at these values.</li>
</ul>
<p>For example, suppose <span class="math inline">\(\texttt{y}\)</span> is a vector of length 20 containing the responses at times <span class="math inline">\(1,\dots,20\)</span>.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># observation times</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>tt<span class="ot">=</span><span class="dv">1</span><span class="sc">:</span><span class="dv">20</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="co"># compute a dense set of numbers between 0 and 21: 0,0.1,...,20.9,21.0</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>ttnew <span class="ot">=</span> (<span class="dv">0</span><span class="sc">:</span><span class="dv">210</span>)<span class="sc">/</span><span class="dv">10</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="co"># compute predicted values at each of 0,0.1,...,20.9,21.0</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>pred<span class="ot">=</span><span class="fu">predict.gam</span>(out,<span class="at">newdata=</span><span class="fu">list</span>(<span class="at">tt=</span>ttnew))</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="co"># plot the original data</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(tt,y)</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="co"># superimpose the smoothing spline</span></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(ttnew,pred)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="coronary-heart-disease-chd-in-south-africa" class="level2" data-number="6.4">
<h2 data-number="6.4" class="anchored" data-anchor-id="coronary-heart-disease-chd-in-south-africa"><span class="header-section-number">6.4</span> Coronary heart disease (CHD) in South Africa</h2>
<p>The textbook <em>Elements of Statistical Learning</em>, by Hastie, Tibshirani and Friedman (2nd Edn, 2011), refers to a case–control study of coronary heart disease (CHD) in South Africa. <!--
The data are available from the authors' website, and may be read directly into **R** with the command:
---></p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>hr <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="st">"https://richardpmann.com/MATH5824/Datasets/SAheart.txt"</span>, <span class="at">sep=</span><span class="st">","</span>,<span class="at">head=</span>T,<span class="at">row.names=</span><span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<table class="table">
<colgroup>
<col style="width: 24%">
<col style="width: 75%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(\texttt{tobacco}\)</span></td>
<td>cumulative tobacco consumption (kg)</td>
</tr>
<tr class="even">
<td><span class="math inline">\(\texttt{famhist}\)</span></td>
<td>family history of heart disease (Present, Absent)</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\texttt{age}\)</span></td>
<td>age at onset of the disease (years)</td>
</tr>
<tr class="even">
<td><span class="math inline">\(\texttt{chd}\)</span></td>
<td>case–control status (1 <span class="math inline">\(\Rightarrow\)</span> CHD; 0 <span class="math inline">\(\Rightarrow\)</span> no CHD).</td>
</tr>
</tbody>
</table>
<p>The dependent variable in our models will be <span class="math inline">\(\texttt{chd}\)</span>. We can consider the CHD status of each individual to be the result of an <em>experiment</em> in which the outcome is either CHD (<em>success</em>) or no CHD (<em>failure</em>). Thus we can model these data using the Binomial distribution, where the Binomial index is 1. The <span class="math inline">\(\texttt{glm}\)</span> function allows such binary (0/1) dependent variables to be specified directly in the model formula, as in the example below, instead of via the usual two-column matrix of successes and failures.</p>
<p>We can examine CHD in relation to tobacco consumption, age and family history of heart disease, with the following <strong>R</strong> commands:</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># make variables in dataframe hr directly available</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">attach</span>(hr)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="co"># fit a generalised linear model with chd as dependent variable</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>glm1 <span class="ot">=</span> <span class="fu">glm</span>(<span class="at">formula=</span><span class="st">'chd~tobacco+age+famhist'</span>,<span class="at">family=</span><span class="st">'binomial'</span>)</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a><span class="co"># examine the results</span></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(glm1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = "chd~tobacco+age+famhist", family = "binomial")

Coefficients:
                Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)    -3.620593   0.444576  -8.144 3.83e-16 ***
tobacco         0.083004   0.025712   3.228  0.00125 ** 
age             0.048812   0.009452   5.164 2.42e-07 ***
famhistPresent  0.974791   0.220023   4.430 9.41e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 596.11  on 461  degrees of freedom
Residual deviance: 495.39  on 458  degrees of freedom
AIC: 503.39

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
<p>All variables in this model are statistically significant: disease is positively related to the amount of tobacco consumed, age and family history of heart disease. However, this model assumes that the logit of the probability of disease is <em>linearly</em> related to both tobacco consumption and age (logit being the default link for Binomial). We can explore more flexible tobacco-consumption and age trends with the following generalised additive model:</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mgcv)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: nlme</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>This is mgcv 1.9-0. For overview type 'help("mgcv-package")'.</code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>gam1 <span class="ot">=</span> <span class="fu">gam</span>(chd <span class="sc">~</span> <span class="fu">s</span>(tobacco,<span class="at">k=</span><span class="dv">20</span>)<span class="sc">+</span><span class="fu">s</span>(age,<span class="at">k=</span><span class="dv">20</span>)<span class="sc">+</span>famhist, <span class="at">family=</span><span class="st">'binomial'</span>)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary.gam</span>(gam1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Family: binomial 
Link function: logit 

Formula:
chd ~ s(tobacco, k = 20) + s(age, k = 20) + famhist

Parametric coefficients:
               Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)     -1.2379     0.1631  -7.592 3.15e-14 ***
famhistPresent   0.9628     0.2233   4.311 1.62e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Approximate significance of smooth terms:
             edf Ref.df Chi.sq  p-value    
s(tobacco) 6.080  7.573  17.89   0.0179 *  
s(age)     1.002  1.003  24.11 9.53e-07 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

R-sq.(adj) =  0.212   Deviance explained = 19.1%
UBRE = 0.083268  Scale est. = 1         n = 462</code></pre>
</div>
</div>
<p>Here, the <span class="math inline">\(\texttt{s}\)</span> function specifies a smooth (cubic spline) dependence. Parameter <span class="math inline">\(\texttt{k}\)</span> of the <span class="math inline">\(\texttt{s}\)</span> function specifies the maximum number of degrees of freedom to be allocated to this dependence. Setting <span class="math inline">\(\texttt{k}\)</span> too small would restrict the set of basis functions used to construct the splines; setting <span class="math inline">\(\texttt{k}\)</span> too large would increase the computational burden unnecessarily.</p>
<p>These results show that the fitted smoothing spline of the dependence of CHD on tobacco consumption has an <em>effective degrees of freedom</em> (edf) of 6.080, while the dependence on age has edf of only 1.002, implying an almost linear age-dependence because a linear age term would have exactly 1 degree of freedom. See Section <a href="5_smoothingparameter.html#sec-edf"><span>Section&nbsp;5.5</span></a> for further details on the calculation of edf.</p>
<p>The significance of each of these smooth terms is given by the <span class="math inline">\(p\)</span>-value column in the above table. These <span class="math inline">\(p\)</span>-values are computed from the <span class="math inline">\(\chi^2\)</span> statistics in the previous column whose approximate degrees of freedom are given in the column headed <span class="math inline">\(\texttt{Ref.df}\)</span>. For example, the <span class="math inline">\(p\)</span>-value of 0.0196 for <span class="math inline">\(\texttt{s(tobacco)}\)</span> is computed by referring 17.62 to the <span class="math inline">\(\chi^2\)</span> distribution on 7.573 degrees of freedom. Note that this compares the above model with the model which omits <span class="math inline">\(\texttt{tobacco}\)</span> completely.</p>
<p>The following <strong>R</strong> code was used to plot the fitted smooth functions of age and tobacco consumption:</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># for larger axis labels</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">cex.lab=</span><span class="fl">1.6</span>)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="co"># create synthetic data set for ages 15 to 65 having consumed</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="co"># no tobacco and with no family history of heart disease</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>newdat1 <span class="ot">=</span> <span class="fu">data.frame</span>(<span class="at">age =</span> <span class="fu">seq</span>(<span class="at">from=</span><span class="dv">15</span>,<span class="at">to=</span><span class="dv">65</span>,<span class="at">by=</span><span class="fl">0.1</span>),<span class="at">tobacco=</span><span class="dv">0</span>,</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>          <span class="at">famhist=</span><span class="st">"Absent"</span>)</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a><span class="co"># predict logit probability of CHD in these synthetic individuals</span></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>pred1 <span class="ot">=</span> <span class="fu">predict.gam</span>(gam1,<span class="at">newdata=</span>newdat1)</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a><span class="co"># plot the predicted logit probability of CHD by age in these</span></span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a><span class="co"># synthetic individuals</span></span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(newdat1<span class="sc">$</span>age,pred1,<span class="at">xlab=</span><span class="st">"Age"</span>,</span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">ylab=</span><span class="st">"Predicted logit probability of CHD"</span>, <span class="at">type=</span><span class="st">"l"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="6_smoothinginpractice_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="672"></p>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># create synthetic data set for age 40 having consumed tobacco</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="co"># ranging from 0 to 32kg and with no family history  of heart disease</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>newdat2 <span class="ot">=</span> <span class="fu">data.frame</span>(<span class="at">age =</span> <span class="dv">40</span>,<span class="at">tobacco=</span><span class="fu">seq</span>(<span class="at">from=</span><span class="dv">0</span>,<span class="at">to=</span><span class="dv">32</span>,<span class="at">by=</span><span class="fl">0.1</span>),</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>          <span class="at">famhist=</span><span class="st">"Absent"</span>)</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a><span class="co"># predict logit probability of CHD in these synthetic individuals</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>pred2 <span class="ot">=</span> <span class="fu">predict.gam</span>(gam1,<span class="at">newdata=</span>newdat2)</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a><span class="co"># plot the predicted logit probability of CHD by tobacco in these imaginary individuals</span></span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(newdat2<span class="sc">$</span>tobacco,pred2,<span class="at">xlab=</span><span class="st">"Tobacco consumption"</span>,</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">ylab=</span><span class="st">"logit probability of CHD"</span>, <span class="at">type=</span><span class="st">"l"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="6_smoothinginpractice_files/figure-html/unnamed-chunk-6-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The predicted dependence of the logit probability of CHD on smooth functions of age and tobacco consumption is shown above. We see an almost linear predicted age-dependence, in agreement with its edf. The curious predicted dependence on tobacco consumption might be explained by other factors correlated with tobacco consumption.</p>
<!--
## Exercise


::: {.webex-box}
6.1

:::



::: {.callout-note appearance="default"}
[Exercise 6 Solutions can be found here.](https://richardpmann.com/MATH5824/Solutions_6.html)
-->


</section>

</main> <!-- /main -->
<script>

/* update total correct if #webex-total_correct exists */
update_total_correct = function() {
  console.log("webex: update total_correct");

  var t = document.getElementsByClassName("webex-total_correct");
  for (var i = 0; i < t.length; i++) {
    p = t[i].parentElement;
    var correct = p.getElementsByClassName("webex-correct").length;
    var solvemes = p.getElementsByClassName("webex-solveme").length;
    var radiogroups = p.getElementsByClassName("webex-radiogroup").length;
    var selects = p.getElementsByClassName("webex-select").length;

    t[i].innerHTML = correct + " of " + (solvemes + radiogroups + selects) + " correct";
  }
}

/* webex-solution button toggling function */
b_func = function() {
  console.log("webex: toggle hide");

  var cl = this.parentElement.classList;
  if (cl.contains('open')) {
    cl.remove("open");
  } else {
    cl.add("open");
  }
}

/* check answers */
check_func = function() {
  console.log("webex: check answers");

  var cl = this.parentElement.classList;
  if (cl.contains('unchecked')) {
    cl.remove("unchecked");
    this.innerHTML = "Hide Answers";
  } else {
    cl.add("unchecked");
    this.innerHTML = "Show Answers";
  }
}

/* function for checking solveme answers */
solveme_func = function(e) {
  console.log("webex: check solveme");

  var real_answers = JSON.parse(this.dataset.answer);
  var my_answer = this.value;
  var cl = this.classList;
  if (cl.contains("ignorecase")) {
    my_answer = my_answer.toLowerCase();
  }
  if (cl.contains("nospaces")) {
    my_answer = my_answer.replace(/ /g, "")
  }

  if (my_answer == "") {
    cl.remove("webex-correct");
    cl.remove("webex-incorrect");
  } else if (real_answers.includes(my_answer)) {
    cl.add("webex-correct");
    cl.remove("webex-incorrect");
  } else {
    cl.add("webex-incorrect");
    cl.remove("webex-correct");
  }

  // match numeric answers within a specified tolerance
  if(this.dataset.tol > 0){
    var tol = JSON.parse(this.dataset.tol);
    var matches = real_answers.map(x => Math.abs(x - my_answer) < tol)
    if (matches.reduce((a, b) => a + b, 0) > 0) {
      cl.add("webex-correct");
    } else {
      cl.remove("webex-correct");
    }
  }

  // added regex bit
  if (cl.contains("regex")){
    answer_regex = RegExp(real_answers.join("|"))
    if (answer_regex.test(my_answer)) {
      cl.add("webex-correct");
    }
  }

  update_total_correct();
}

/* function for checking select answers */
select_func = function(e) {
  console.log("webex: check select");

  var cl = this.classList

  /* add style */
  cl.remove("webex-incorrect");
  cl.remove("webex-correct");
  if (this.value == "answer") {
    cl.add("webex-correct");
  } else if (this.value != "blank") {
    cl.add("webex-incorrect");
  }

  update_total_correct();
}

/* function for checking radiogroups answers */
radiogroups_func = function(e) {
  console.log("webex: check radiogroups");

  var checked_button = document.querySelector('input[name=' + this.id + ']:checked');
  var cl = checked_button.parentElement.classList;
  var labels = checked_button.parentElement.parentElement.children;

  /* get rid of styles */
  for (i = 0; i < labels.length; i++) {
    labels[i].classList.remove("webex-incorrect");
    labels[i].classList.remove("webex-correct");
  }

  /* add style */
  if (checked_button.value == "answer") {
    cl.add("webex-correct");
  } else {
    cl.add("webex-incorrect");
  }

  update_total_correct();
}

window.onload = function() {
  console.log("webex onload");
  /* set up solution buttons */
  var buttons = document.getElementsByTagName("button");

  for (var i = 0; i < buttons.length; i++) {
    if (buttons[i].parentElement.classList.contains('webex-solution')) {
      buttons[i].onclick = b_func;
    }
  }

  var check_sections = document.getElementsByClassName("webex-check");
  console.log("check:", check_sections.length);
  for (var i = 0; i < check_sections.length; i++) {
    check_sections[i].classList.add("unchecked");

    let btn = document.createElement("button");
    btn.innerHTML = "Show Answers";
    btn.classList.add("webex-check-button");
    btn.onclick = check_func;
    check_sections[i].appendChild(btn);

    let spn = document.createElement("span");
    spn.classList.add("webex-total_correct");
    check_sections[i].appendChild(spn);
  }

  /* set up webex-solveme inputs */
  var solveme = document.getElementsByClassName("webex-solveme");

  for (var i = 0; i < solveme.length; i++) {
    /* make sure input boxes don't auto-anything */
    solveme[i].setAttribute("autocomplete","off");
    solveme[i].setAttribute("autocorrect", "off");
    solveme[i].setAttribute("autocapitalize", "off");
    solveme[i].setAttribute("spellcheck", "false");
    solveme[i].value = "";

    /* adjust answer for ignorecase or nospaces */
    var cl = solveme[i].classList;
    var real_answer = solveme[i].dataset.answer;
    if (cl.contains("ignorecase")) {
      real_answer = real_answer.toLowerCase();
    }
    if (cl.contains("nospaces")) {
      real_answer = real_answer.replace(/ /g, "");
    }
    solveme[i].dataset.answer = real_answer;

    /* attach checking function */
    solveme[i].onkeyup = solveme_func;
    solveme[i].onchange = solveme_func;

    solveme[i].insertAdjacentHTML("afterend", " <span class='webex-icon'></span>")
  }

  /* set up radiogroups */
  var radiogroups = document.getElementsByClassName("webex-radiogroup");
  for (var i = 0; i < radiogroups.length; i++) {
    radiogroups[i].onchange = radiogroups_func;
  }

  /* set up selects */
  var selects = document.getElementsByClassName("webex-select");
  for (var i = 0; i < selects.length; i++) {
    selects[i].onchange = select_func;
    selects[i].insertAdjacentHTML("afterend", " <span class='webex-icon'></span>")
  }

  update_total_correct();
}

</script>
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./5_smoothingparameter.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Choosing the Smoothing Parameter</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
  </div>
</nav>
</div> <!-- /content -->



</body></html>